### ISSUE TITLE
Upload error on big rasters

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#100]
# Problem

When trying to upload raster layers that are big (>100mb) the upload fails with an error.

![upload_error](https://cloud.githubusercontent.com/assets/2510900/24865999/3e0c3b92-1e09-11e7-9f43-e715c53c6420.png)

# Solution
* The large rasters can be uploaded with geonode management commands which can only be done by people with server access.
* There is a timeout setting in geonode - Increase this and test
* Fix any how to make it happy

**Comment by gubuntu** [comment]
@NyakudyaA this is a geonode issue, not a geosafe one. Please move to https://github.com/kartoza/geonode and reference it in #96

**Comment by NyakudyaA** [comment]
Ok. Sorry I will move it in the right place

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#278
