### ISSUE TITLE
fix layout issue in safari

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#112]
https://files.gitter.im/kartoza/kartoza/rNmp/Screen-Shot-2017-05-12-at-9.43.56-AM.png

**Comment by NyakudyaA** [comment]
Also visible in ubuntu firefox

**Comment by boney-bun** [comment]
I don't fully understand the issue here. do you mean that the zoom in and zoom out button must align to the left? It's not only on safari, but also on chrome and firefox as well.

**Comment by gubuntu** [comment]
yes they must align like they do in the current version.

**Comment by boney-bun** [comment]
@gubuntu I've looked at the codes. also, tried on edge browser. it has the same problem. I guess it's related to the js library instead. we use [angular-leaftlet](https://github.com/tombatossals/angular-leaflet-directive) which is outdated for now. we may need to modify the js to suit our need.

**Comment by dimasciput** [comment]
I think you can fix this by modify the css.

**Comment by gubuntu** [comment]
@boney this should be a simple css fix. It's correct in the old version on geonode.kartoza.com
