### ISSUE TITLE
pass current view extent to celery

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#113]
send bounding box as part of the celery job paramaters to inaSAFE so that inaSAFE clips input layers (with uri, not url)

**Comment by gubuntu** [comment]
The analysis extent to use must be the interesection of the hazard layer, exposure layer and view extent. (overlaps with #78)

**Comment by lucernae** [comment]
We can say we implemented this. The extent used is the view extent (then it will check if it is intersected with hazard and exposure and gives warning).

**Comment by gubuntu** [comment]
but does it actually perform the intersection and then send the intersection through as the analysis extent?

**Comment by gubuntu** [comment]
@lucernae this is complete, right? Please close
