### ISSUE TITLE
improve analysis flow

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#114]
from @boney-bun

>The pop-up windows are helpful in assisting users step-by-step to run an analysis. However, the “Run Analysis” always shows up after selecting exposure and hazard. Another concern is how to reset the filters? Refresh the page won’t work.

(is this still the case @boney-bun)

**Comment by boney-bun** [comment]
I'm not sure @gubuntu 
we need more working data sample to find out.
I only know 1 pair of working exposure and hazard layers.
I'll come back to this issue when we have sufficient working layers.
I'm talking about the case for geonode 2.7 and geosafe 2.6.x.

**Comment by gubuntu** [comment]
there are several more layers now that @NyakudyaA has been loading. And yes the test environment you mention is correct.

**Comment by boney-bun** [comment]
i can confirm that this ticket is no longer valid.
"Run Analysis" shows only after the hazard and exposure layers are selected.
and we already have `start again` button (similar to reset).
can we close this ticket @gubuntu ?
