### ISSUE TITLE
More paper cuts for InaSAFE Create Analysis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#118]
_From @timlinux on May 13, 2016 9:36_

## Fix pop out titles:
- [x] Select a population layer
- [x] Select the structure -> Select a structure layer
- [x] Select a roads layer
- [x] Select a flood layer
- [x] Select a tsunami layer   **needs to be added**
- [x] Select an impact layer
## IF button

If layers are not appropriate to provide an valid IF, show this text in the pop out:

> No impact functions are available. In order to run the analysis you need to select one hazard layer (flood, tsunami, volcano, earthquake etc.) and one exposure layer (population, structure, roads).

_Copied from original issue: kartoza/geonode#53_

**Comment by gubuntu** [comment]
_From @lucernae on May 13, 2016 9:37_

- [x] pop up when there is empty impact layer should encourage user to create analysis instead of uploading a layer

**Comment by gubuntu** [comment]
_From @timlinux on June 6, 2016 9:29_

We should add landcover exposure too.

**Comment by gubuntu** [comment]
can you comment on this @myarjunar ?

**Comment by NyakudyaA** [comment]
Select a tsunami layer has been added.
![tsunami](https://user-images.githubusercontent.com/2510900/48488235-f44fb380-e828-11e8-82e9-2136cb0b2650.png)
