### ISSUE TITLE
zoom to global view zooms to multiple world extents

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#122]
In the Analysis view, clicking on the 'zoom to global' button should zoom to one world....i.e. the same extent as the default 'on-load' extent. 

At the moment it zooms out way too far:

<img width="1677" alt="screen shot 2017-06-12 at 09 09 04" src="https://user-images.githubusercontent.com/496911/27022571-e4208044-4f4e-11e7-9469-ba2cd4598056.png">

**Comment by Gustry** [comment]
@gubuntu is looking at the map view : http://staging.geonode.kartoza.com/maps/84

**Comment by boney-bun** [comment]
@Gustry the link is no longer valid. do you have another example so I can replicate this issue locally?

**Comment by boney-bun** [comment]
@gubuntu the current view of create analysis page is:
![screen shot 2017-06-09 at 1 34 36 pm](https://user-images.githubusercontent.com/4602383/27010876-1d9bed20-4ed9-11e7-9bdb-21c929c70277.png)
do you mean to be zoomed out a little bit more so that the asian continent fully shows  up?

**Comment by boney-bun** [comment]
@gubuntu what do you think of this initial map on create analysis page:
![screen shot 2017-06-12 at 1 29 30 pm](https://user-images.githubusercontent.com/4602383/27021520-39c4fbc8-4f73-11e7-8e43-ec4965e2257a.png)

**Comment by gubuntu** [comment]
no, please see my updated OP

**Comment by boney-bun** [comment]
so, basically the zoom out level has minimum value now. once the zoom level reaches its minimum value, the zoom out button is disabled.
![limit-zoom-out-122](https://user-images.githubusercontent.com/4602383/27039731-fe59eab2-4fb8-11e7-9d32-8cbf9831b4de.gif)

**Comment by gubuntu** [comment]
That is OK, but does not solve the problem in the OP.

The OP refers to this button: 
<img width="63" alt="screen shot 2017-06-13 at 14 06 32" src="https://user-images.githubusercontent.com/496911/27081627-927c0efe-5041-11e7-96d7-14b3edff07c0.png">

**Comment by boney-bun** [comment]
![global_to_zoom126](https://user-images.githubusercontent.com/4602383/27118153-2d376ea8-5104-11e7-96d5-85aca44728e9.gif)
do you think it's enough for showing the one world @gubuntu ?

**Comment by gubuntu** [comment]
LGTM
