### ISSUE TITLE
Transparency slider makes map panning

### ISSUE THREAD

**Issue by Gustry** [kartoza/geosafe#124]
If you use the mouse to set the transparency, it makes a pan on the map at the same time. This is not expected.

![move_map](https://cloud.githubusercontent.com/assets/1609292/26668151/fbf34660-46da-11e7-9531-7b725868fb50.gif)

And the slider is not working for transparency:
![transparency](https://cloud.githubusercontent.com/assets/1609292/26668660/5671bcd2-46dd-11e7-82bc-561d6b9afe21.gif)

Also, you can notice some small UI problems with the white background and the border : 
<img width="270" alt="screen shot 2017-06-01 at 15 01 33" src="https://cloud.githubusercontent.com/assets/1609292/26668194/2ec2b634-46db-11e7-8648-b64045d5c0a4.png">

* the black border in the bottom corners
* white background below and above "Legend"

I'm using Safari

**Comment by boney-bun** [comment]
This problem is addressed in #101. I'll close this issue once #101 has been reviewed.
