### ISSUE TITLE
Better landing page text

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#126]
> GeoSAFE is a django app that integrates inaSAFE Headless functionality into Geonode.
> This app visually analyzes an impact on a map in the event of disaster.
> Analysis reports can also be generated and saved for future reference.

I think the first line is not very informative for the average user and should be replaced with:

"GeoSAFE is a web platform that provides the ability to run InaSAFE analyses online. InaSAFE is free software that produces realistic natural hazard impact scenarios for better planning, preparedness and response activities. It provides a simple but rigorous way to combine data from scientists, local governments and communities to provide insights into the likely impacts of future disaster events. You can find out more about the InaSAFE project at http://inasafe.org"

**Comment by boney-bun** [comment]
@timlinux seems to be a better explanation. I can edit the text accordingly and merge into kartoza/geosafe#62. what do you think @gubuntu?

**Comment by ismailsunni** [comment]
Yes @boney-bun please do it in your PR. It only changes the text anyway.
Thanks

**Comment by boney-bun** [comment]
it's still in backlog, yet I have revised the text accordingly based on the PR for kartoza/geosafe#62. should we close this issue then?
