### ISSUE TITLE
Analysis keeps spinning and nothing happens

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#142]
I selected the flood layer from Radarsat in Malawi and then the road layer. Nothing happens after clicking on the exposure layer and the analysis icon keeps spinning....

![jun-23-2017 09-19-01](https://user-images.githubusercontent.com/10201533/27491004-67a6cf6e-57f5-11e7-9d36-222be3c92808.gif)

**Comment by gubuntu** [comment]
we'll be filtering out layer combinations that don't work on staging, whether it's because of a bug or a size or performance issue. Also, work on these issues should make many more combinations work reliably and faster this week: 
- https://github.com/kartoza/geosafe/issues/137
- https://github.com/kartoza/geosafe/issues/54
- https://github.com/kartoza/geosafe/issues/113
- https://github.com/kartoza/docker-geosafe/issues/41

**Comment by gubuntu** [comment]
staging still doing this. I zoomed right in to test the effect of the new clip boundary but it zoomed out to the layer extent when I hit run. I don't think it should zoom out. 

![Screen Shot 2017-06-26 at 12.16.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f56b7191a379ed0c2a57415b49be5d4a1f06a3a3dc78e2a436628f545aef85650920923c44a9ed824aed01ba26df48d1b2b99850d2aa6c7bb3d4d216744b470a83ed5e37aa984fc150f24ce34e5da61b3360f43b.png)

**Comment by lucernae** [comment]
I thought it would fix it right away.
If this is the case, then perhaps InaSAFE itself doesn't clip the layer at first and only clips it after analysis. This makes the analysis process will still take a long time.
I will investigate this more.

**Comment by lucernae** [comment]
@gubuntu , I tried it again with smaller analysis extent and it works. So your extent probably very big, so it takes a long time finish. At the moment, I set the area warning limit to 1000 km^2. If the extent exceeded that, there will be a warning in analysis confirmation dialog (but user can still do the analysis). Also, the analysis run time limit is 10 mins. If it exceeded that, the job will cancel. We can also configure this. Do you have any additional suggestion to make the user comfortable with this interaction?

**Comment by gubuntu** [comment]
Thanks @lucernae, it's good that we're getting a handle on processing thresholds and system limitations. If the interaction works reliably as you state above I think that is good for now. 

The production instance, with more, distributed, resources should reduce processing time or increase the size threshold.  

Let's focus on stabilising and performance now and wait for feedback on the interaction.

**Comment by gubuntu** [comment]
This has been addressed by limiting analysis extents and performance enhancement
