### ISSUE TITLE
"Dartmouth Flood Malawi" layer not rendering correctly?

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#143]
The entire layer is blue, stretching/classes must be adjusted.

There's a strange blue artifact in the lower right corner, over the ocean.

The legend is missing the layer title.

There are some issues with the background layer.

![screen shot 2017-06-23 at 09 24 35](https://user-images.githubusercontent.com/10201533/27491187-313b7d3e-57f6-11e7-86ca-ceda6d996e4a.jpg)

**Comment by NyakudyaA** [comment]
![units](https://user-images.githubusercontent.com/2510900/27782090-4bdf691a-5fd1-11e7-95ae-3f657d6e3617.png)

@boney-bun  Can you comment on the legend missing  the layer title

**Comment by gubuntu** [comment]
@boney-bun @NyakudyaA pls wrap this up and close

**Comment by NyakudyaA** [comment]
The name is visible in staging. The layer renders fine in production.
