### ISSUE TITLE
Layers don't have names

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#144]
Looking at population layers for Madagascar, it's not clear from the current name what they are. The legend also shows only two classes, black (0) and white (1.50367), without any explanation or units. The analysis icon keeps spinning and nothing happens.

![screen shot 2017-06-23 at 09 46 00](https://user-images.githubusercontent.com/10201533/27492074-b704335e-57f9-11e7-99bf-3da7a00b5c99.jpg)

**Comment by NyakudyaA** [comment]
@cgiovando  @gubuntu  The layer names comes from the name of the raster/vector layer that has been uploaded.  Each time staging is being redeployed the layers names are reverting to the old one even in cases where I have changed them. On production, all layers will be having good clear names.

I thought the metadata could be used to describe what the values mean. I can adjust this. For population count what units should be indicated on the legend and for population density what units should be indicated?

**Comment by gubuntu** [comment]
population count unit: people per cell (people/cell)
density unit: people per km<sup>2</sup> (people/km<sup>2</sup>)

in both cases you'll have to check the metadata or read up on the data set to make sure these are correct. Count could be 'thousand people per cell' and density could be 'people per square metre', for example. 

Redeploying should not be re-loading existing data sets and changing their names @NyakudyaA - there is another ticket for this but it is not important today. We're only worried about production for the launch

**Comment by gubuntu** [comment]
Please confirm that all production layers have nice names and close

**Comment by NyakudyaA** [comment]
All layer names in production have nice names
