### ISSUE TITLE
Please add to the footer of GeoSAFE pages a link to the git repo

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#148]
Will be useful for people to file tickets etc.

**Comment by boney-bun** [comment]
as a start, would this work @timlinux ?
![geosafe148](https://user-images.githubusercontent.com/4602383/27514745-dc2f84ce-59bd-11e7-9332-456dd105414b.png)

**Comment by gubuntu** [comment]
'To contribute to the GeoSAFE project or to report any issues, head over to the GeoSAFE repository'

**Comment by boney-bun** [comment]
![screen shot 2017-06-27 at 8 52 25 pm](https://user-images.githubusercontent.com/4602383/27591454-e5a58d90-5b7b-11e7-9a9d-e058f24a8766.png)
