### ISSUE TITLE
tweak not logged in notification

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#149]
1. 'please login to save analysis' should read 'please sign in to save analysis' and the 'sign in' should be a link sign in (ideally without leaving analysis page?) 
2. when other messages about the analysis come up they obscure the sign in warning message. These message should appear side by side or above one another rather than on top of each other.

**Comment by boney-bun** [comment]
let me know what do you think of this enhanced version @gubuntu
![tweak149](https://user-images.githubusercontent.com/4602383/27518240-7fbdb128-5a05-11e7-8116-6face8a38d45.gif)

**Comment by gubuntu** [comment]
nice!
