### ISSUE TITLE
Fix download options for analysis results

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#15]
# Problem

After running analysis the results are listed in the analysis lists. 

![down](https://cloud.githubusercontent.com/assets/2510900/21048893/57def8b0-be1a-11e6-9e2a-be2f7971f229.png)

There is a download option and it downloads the results and layers which were used in running the analysis. Downloading the layers should be an option but the results should be mandatory downloaded. There should be a distinction between products and inputs of analysis. Downloading the layers is an overkill as some of the layers are very big.

# Solution
Fix. 
Aggregate results table and Map table so that they can be downloaded together without the impact layers.
Add an option to download the impact layers separately.

Add tips that show that when a user clicks download what is being downloaded.

**Comment by gubuntu** [comment]
@NyakudyaA please test again and comment

**Comment by NyakudyaA** [comment]
Tho download applies to results and when a user navigates to the analysis page he has more options to download
![options](https://user-images.githubusercontent.com/2510900/46721576-a0730d00-cc73-11e8-9540-841a55fd8abe.png)
