### ISSUE TITLE
Layer should be able to be toggled

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#152]
In previous version of GeoSAFE, this interaction exists:

Analysis creation:
1. Click a layer (hazard/exposure) from side panel --> tiles will show up in the map
2. Click the same layer again from side panel --> tiles will not show up in the map
3. Click the same layer again from side panel --> tiles show up again

Now the interaction stuck at 2. We can't re-add the same layer again, it just won't accept same layer.

Proposal:
I did some light debugging and found out that the layer can't be added because it was exists in variable called layer_stack (related with transparency control). Perhaps you should do some bug fixing for that, since you know these code better 😛 . I tried to fix it myself, but it's not quite obvious for me, so maybe it was better for me to do something else.

**Comment by gubuntu** [comment]
seems to be part of #67

**Comment by boney-bun** [comment]
i am able to replicate the problem on my local.
i didn't consider this use case before: user select - deselect - and select a same layer.
let me try to solve this.
this ticket is different from #67 @gubuntu

**Comment by boney-bun** [comment]
the use case has taken care now :)
![selectdeselect152](https://user-images.githubusercontent.com/4602383/27579085-7f1a9eb0-5b50-11e7-96be-e5e656d09929.gif)
