### ISSUE TITLE
Rectangle showed up after analysis

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#154]
Le rectangle showed up in the analysis layer after running analysis:

Is this a bug or feature?

CC @boney-bun ?

**Comment by gubuntu** [comment]
@lucernae are you referring to the orange filled rectangles?

@boney-bun those orange rectangles get in the way, what are they? They should not draw or instead be outlines only

**Comment by boney-bun** [comment]
fixed.

![fixbboxinanalysis154](https://user-images.githubusercontent.com/4602383/27624871-ba062a0a-5c0c-11e7-9547-e51e76628e43.gif)
