### ISSUE TITLE
Add layer name to Analysis List in all cases

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#158]
Currently, layer name is reported on Success. 

The layer name the user chose (or the system generated) should be reported also in Pending and Failure states.

**Comment by boney-bun** [comment]
fixed.
* the previous Analysis List:
![screen shot 2017-07-13 at 11 53 05 pm](https://user-images.githubusercontent.com/4602383/28178607-4b1352b6-6829-11e7-9225-e966f27a1cb9.png)
* Analysis List when a user not log in:
![screen shot 2017-07-14 at 12 11 31 am](https://user-images.githubusercontent.com/4602383/28178641-65895e9c-6829-11e7-9644-6b8c5f416d4b.png)
* Analysis List when a user log in (additional `Cancel Analysis` button on `pending` status):
![screen shot 2017-07-14 at 12 12 43 am](https://user-images.githubusercontent.com/4602383/28178664-71bbf65c-6829-11e7-864f-b37350c1a01f.png)

**Comment by gubuntu** [comment]
LGTM - nice work @boney-bun
