### ISSUE TITLE
throughly test the UI on staging

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#159]
After changes have been merged and deployed, fully and critically test all functionality from a user perspective as a matter of routine. 

Proactively go back and fix or raise issues

**Comment by boney-bun** [comment]
as a start, here is the link for the testing @gubuntu 
if there are some new commits, I would add them to the testing scenario.
https://docs.google.com/a/kartoza.com/spreadsheets/d/1YXK3BAZHnUUHd0WYzVfO1dRHTrp4wTmgbe7m6wSjGpU/edit?usp=sharing

**Comment by gubuntu** [comment]
nice @boney-bun

**Comment by boney-bun** [comment]
could we close this ticket @gubuntu ? or, do you need me to keep testing the staging, at the least, when there is a new merge on the repo?

**Comment by gubuntu** [comment]
we'll close this, but keep up the testing routine!
