### ISSUE TITLE
improve analysis loading experience

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#161]
While it loads, the analysis pages remains blank for a long pause and shows the legend skeleton.

Manage loading so something shows immediately or at least have a spinner or message. 

Don't show the legend until it's populated.

**Comment by boney-bun** [comment]
let me know what's your opinion @gubuntu 
![enhanceuserexp161](https://user-images.githubusercontent.com/4602383/28176908-37259e90-6823-11e7-93aa-797ce8895057.gif)

**Comment by gubuntu** [comment]
assuming the legend still does appear when the user selects a layer, this looks good to go
