### ISSUE TITLE
Failed processing does not stop even when analysis has failed

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#165]
# Problem
With the new functionality that kills the long running process, the processing dialog is still active even in situations where the analysis has failed.

![process](https://user-images.githubusercontent.com/2510900/27595012-bd95aa3a-5b5b-11e7-93ec-9a6c977e7bc5.png)

In the analysis list the process has already failed.
![error](https://user-images.githubusercontent.com/2510900/27595066-e4914aea-5b5b-11e7-92f4-c44aebae95dc.png)

# Solution
Make sure that the processing dialog closes as soon as the analysis fails and make sure the error message pops up for a user describing the error.

**Comment by lucernae** [comment]
I thought I already handled this, the dialog will be replaced by an Error message, but the check done every minute, so it's not instantly changed.

I will test this again in my local

**Comment by NyakudyaA** [comment]
@lucernae Ok.

**Comment by gubuntu** [comment]
@NyakudyaA please check and close if fixed

**Comment by NyakudyaA** [comment]
I will close it's fixed now.
