### ISSUE TITLE
Transparency changes extent of layer

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#167]
# Problem
I have zoomed into a particular area and when I change the transparency of a hazard layer it changes the extent slightly.

![output](https://user-images.githubusercontent.com/2510900/27606909-4876aa66-5b82-11e7-9f8c-785b9bcabbef.gif)

# Solution
layer transparency should not affect the extent of the layer. A user  should be able to compare feature at whatever extent

**Comment by boney-bun** [comment]
fixed
![transparencyextent167](https://user-images.githubusercontent.com/4602383/27673743-8d363b94-5ccc-11e7-86d0-5c4863000e26.gif)

PS: i use shift technique to zoom in. thanks @NyakudyaA 😄

**Comment by NyakudyaA** [comment]
@boney-bun  LGMT
