### ISSUE TITLE
Layer legends must have units

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#171]
Ensure layer legends have units

**Comment by NyakudyaA** [comment]
I do not understand. What kind of units should be applied to population count?

**Comment by gubuntu** [comment]
Please check, some layers still do not have units (e.g. malawi flood)

Population count units would be something like 'number of people per cell'

**Comment by NyakudyaA** [comment]
All population layers have been added units.

**Comment by cgiovando** [comment]
@erikkbethke please add units for "Madagascar Tropical Cyclone" layer and any other that are missing. (through QML upload, added for each class label or in the legend layer header)

**Comment by gubuntu** [comment]
@ErikKBethke and @NyakudyaA please close if done on the layers in http://88.99.33.48/ (which was geonode.kartoza.com till a few days ago)... or wait until all layers have been migrated to the new production site and test there.

**Comment by ErikKBethke** [comment]
I will look through the http://88.99.33.48/ and double check that all units are added to the layers.

**Comment by ErikKBethke** [comment]
Are all layers migrated to the new production site? I am not able to access http://88.99.33.48/ any longer and want to be able to finish this.

**Comment by gubuntu** [comment]
@lucernae or @boney-bun please configure 88.99.33.48 to load the old production site (i.e. raw IP must load geonode.kartoza.com)

@ErikKBethke the layers are now on the final demo/production server at http://geonode.kartoza.com

**Comment by lucernae** [comment]
@gubuntu You now able to access it by raw IP http://88.99.33.48/
Ping me back if you want to assign hostname (I need to change nginx forward rule).

**Comment by gubuntu** [comment]
http://88.99.33.48/ is the previous server where we have a full curated list of layers

http://geonode.kartoza.com is the new production server that we are using to demo today and which will have just a few working layers
