### ISSUE TITLE
clicking on exposure zooms to layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#174]
only hazard selection must zoom to hazard layer. 

Now, if you select a global exposure layer after selecting a local hazard layer, it zooms out to the exposure layer extent again! 

Regressions like this must get through to staging let alone production.

**Comment by boney-bun** [comment]
this is the default behaviour on the UI. 
maybe it is there  to pinpoint the layer location to the user.
both layers (hazard and exposure) will be zoom out according to their extent.

do you want me to turn off the zoom behaviour only for exposure layer?

**Comment by gubuntu** [comment]
I think the logic should be: whether you selected hazard or exposure first, if the next one you select is smaller then zoom to it. If it is bigger then do not zoom to it.

**Comment by gubuntu** [comment]
in fact, the best extent to zoom to is the intersection of both layers

**Comment by akbargumbira** [comment]
hi @gubuntu, PR #190 should fix this.
