### ISSUE TITLE
analysis not finishing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#175]
Any analysis on production should work. 

Cristiano tried Malawi floods on people zoomed into a city and it continued past ten minutes with no result (just spinning)

@nyakudya please ensure this and note in the Google sheet if a combination needs to be zoomed in and to what extent. 

@lucernae pls continue troubleshooting and getting to the bottom of this

**Comment by NyakudyaA** [comment]
On production, there are no rasters for Malawi because they are not showing up correct extent.  In cases where I have indicated that analysis is running when zoomed in a user should zoom in until the warning message about size does not show up.

**Comment by gubuntu** [comment]
what is wrong with the extent? something you can fix on the data side? CRS?

**Comment by NyakudyaA** [comment]
It's not on the data side because the layer renders properly in QGIS. I think @lucernae  is looking at a related issue with CRS. Will try to project it to 4326 and see if it changes it's behavior

**Comment by NyakudyaA** [comment]
Will close this now. I have updated the google sheet with times and also rendered the Malawi layers in staging with EPSG:4326. The extent issue has to do with projections and is documented in https://github.com/kartoza/geonode/issues/289
