### ISSUE TITLE
Area limit message should be in hectares

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#179]
# Problem
When using the analysis extent the area comes up as square meters. It will be nice to provide them as hectares as meters is not human readable in instances where the area is huge.

![hect](https://user-images.githubusercontent.com/2510900/27757299-24807058-5e00-11e7-9db2-59dc69ec120e.png)

# Solution
Make it happy

**Comment by gubuntu** [comment]
duplicate. please see original ticket OP, it must be sq km.
