### ISSUE TITLE
analysis legend should fit on page or have a scroll down bar

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#180]
# Problem
After running an analysis where the legends of exposure/hazard and resultant analysis are long the legend of the result is not clearly visible.

![fit](https://user-images.githubusercontent.com/2510900/27759840-5deadc18-5e3a-11e7-9c6b-8cb24f5b2939.png)

# Solution

Making the legend appear on the same page might be difficult but if we could have a scroll bar and a user can scroll

**Comment by gubuntu** [comment]
What is the status of this @boney-bun?

**Comment by boney-bun** [comment]
this should be fixed by #188
i will close this issue for now.
