### ISSUE TITLE
Align elements for legends and transparency to the same side

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#181]
# Problem

After running the analysis the legend generated for the result is centered to the left while the hazard and exposure are centered at the middle.

![fit](https://user-images.githubusercontent.com/2510900/27759872-fa197f22-5e3a-11e7-99b8-34c6ec474426.png)

# Solution
Align all elements   on the same side so that it looks nice

**Comment by akbargumbira** [comment]
I think it's already centered, but in the case above, the impact legend has long description

**Comment by NyakudyaA** [comment]
@akbargumbira  so would it not be nice then to left center everything so as to have legends generated with long text to look nice. I hope you agree with me that the way they look is not pleasing

**Comment by gubuntu** [comment]
yes please left justify
