### ISSUE TITLE
Tanzania buildins not drawing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#182]
This could be a software issue or a styling issue.

Eliminate the styling issue by ensuring something draws at all scales - either by filtering or using centroids or something....

hand over to @lucernae if it is a software issue

**Comment by NyakudyaA** [comment]
Building rendering.  Had to set the thumbnail after loading it. Maybe generating thumbnails is associated with the checking of the bounding box happening before thumbnails are generated. Will comment on the relevant issue about thumbnails and bounding box
