### ISSUE TITLE
GeoSAFE tagline

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#198]
from @vdeparday:
>We need to develop a Tag line to go below the GeoSAFE name

child of #306

**Comment by carina1000** [comment]
Hi @gubuntu what do you think of these options:

"InaSafe Analysis made easy"

"Visual Analysis of Disaster Management" / "Analysis of Disaster Management"

"Runs Disaster Management Analysis Easily"

"Realistic Natural Hazard Impact Analysis"

**Comment by gubuntu** [comment]
Let's go with 

"Realistic Natural Hazard Impact Analysis on the Web -- InaSAFE made easy"

**Comment by carina1000** [comment]
Cool - just a note, don't you think 'on the Web' is a bit redundant?

**Comment by gubuntu** [comment]
+1, drop it :-)
