### ISSUE TITLE
add the layers name to the legend

### ISSUE THREAD

**Issue by boney-bun** [kartoza/geosafe#201]
when a user select a layer, show its name on the legend.

**Comment by boney-bun** [comment]
what do you think of this mock up @timlinux ?
![Screen Shot 2017-07-20 at 1.35.36 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f36b7191a379f1112e4f5c595ecc3c4a4356bcbbd671f3e57862804e0ee5806f0b7c906945aded874abf54e8208b49d1b1e88e49d2f42f67b6d5db1063474f4dcbed5727a39841c95df64be44e57a11b3460ef772431.png)

**Comment by gubuntu** [comment]
LGTM, nice work

Please confirm that if the user has given the layer a clear English name (like Admire did in production), that it will use that name and not another field with an 'ugly' name

**Comment by boney-bun** [comment]
yes, it uses clear English name now.
![screen shot 2017-07-24 at 3 05 10 pm](https://user-images.githubusercontent.com/4602383/28513758-8e3a5962-7081-11e7-8a8e-d439aa66f3cd.png)
