### ISSUE TITLE
Prevent analyses with over-threshold extents

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#204]
#78 / #187 just communicate to the user that the analysis might take too long. 

What this ticket requests is that any user-initiated analyses that is over that threshold is prevented from starting.

e.g. if it is over threshold and the user clicks Run, it responds with something like 'please reduce extent and try again'

**Comment by boney-bun** [comment]
it is difficult to assess threshold where there are many factors should be counted in.
so, i would suggest using statistics to obtain threshold as a start.
Let's say the goal is running an analysis for only 1 minute.
Then:
* we can run one layer combination with various extent on the production
* measures the extent that can be finished within  one minute
* takes the average value and uses this value as the threshold.

what do you think @gubuntu ?
or, do you already have a threshold on mind?

once we have threshold i can implement the message on the UI

**Comment by gubuntu** [comment]
That can come later. For now just use the arbitrary threshold we are already using (10 000 sq km?)
