### ISSUE TITLE
Call to action on home page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#219]
Move 'Try it out' icon (flask) with wording right-justified next to GeoSAFE on the home page. It must be obvious and intuitive how to get to GeoSAFE directly. 

@MariaSolovyeva please provide a last once-over review of the home page including how best to achieve this

**Comment by boney-bun** [comment]
would this GIF work @gubuntu @MariaSolovyeva ? 
![landingpageupdate](https://user-images.githubusercontent.com/4602383/30229202-27900a64-950b-11e7-9f63-de6423fe1e9f.gif)

**Comment by gubuntu** [comment]
we need the words as well

**Comment by boney-bun** [comment]
Updated UI:
![screen shot 2017-09-11 at 6 35 22 pm](https://user-images.githubusercontent.com/4602383/30272759-41cadf64-9720-11e7-9927-539bc5a8e4de.png)

**Comment by gubuntu** [comment]
yes. LGTM (as long as the words and icon are both linked to the analysis page)

**Comment by cgiovando** [comment]
Can we put `Try it out` in a button and maybe just remove the flask?

**Comment by boney-bun** [comment]
something like this @cgiovando ?
![landingpageupdate](https://user-images.githubusercontent.com/4602383/30340207-e958a170-981b-11e7-90b7-08609f7318f2.gif)
