### ISSUE TITLE
Better format for description of analysis

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#222]
Currently when the result analysis completes, the description is using the exact layer names and does not have a question mark (e.g. `In the event of tanzania_nsunga_earthquake, how many health_facilities will be affected`). How can we improve it?

**Comment by boney-bun** [comment]
hi @cgiovando 
could these proposed wording suit you?
![screen shot 2017-10-03 at 3 31 02 pm](https://user-images.githubusercontent.com/4602383/31116629-05cf854a-a851-11e7-92c9-ad7a92f87a79.png)
![screen shot 2017-10-03 at 3 29 40 pm](https://user-images.githubusercontent.com/4602383/31116633-09c6992c-a851-11e7-9d56-b616bb31fadb.png)

**Comment by gubuntu** [comment]
Change to 

`In the event of <name of hazard layer>, the number of people in hazard areas in <name of exposure layer> that are likely to be affected is`

and 

`In the event of <name of hazard layer>, the number of buildings in hazard areas in <name of exposure layer> that are likely to be affected is`

**Comment by gubuntu** [comment]
passed on testing
