### ISSUE TITLE
Improve results map

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#223]
Map in analysis result window does not have background reference layer, nor a legend or a scale. In the screenshot below, only yellow dots...

![screen shot 2017-09-12 at 10 13 18](https://user-images.githubusercontent.com/10201533/30315099-27a2cdd0-97a3-11e7-8877-99279177d474.jpg)

**Comment by gubuntu** [comment]
@carina1000 @cgiovando this window has changed a lot with InaSAFE 4. Please comment on the current one on testing or INGC

cc @myarjunar

**Comment by carina1000** [comment]
Currently, the Analysis Result tab looks like this:
 
![screen shot 2018-10-11 at 13 31 29](https://user-images.githubusercontent.com/35214829/46803446-603d8880-cd60-11e8-924e-0cd5a7657433.png)

I think the new one resolves most points made before, however I have some minor suggestions to improve it even more (Hazard areas may need some more input?):
![analysis result suggestion](https://user-images.githubusercontent.com/35214829/46803498-819e7480-cd60-11e8-93f2-eacca27497d5.png)

- Align text "In event of an earthquake..."
- Rearrange icons and increase size
- Get rid of double "close" - it it to top right, as above

**Comment by myarjunar** [comment]
thanks for the input @carina1000 ! here is the update https://github.com/kartoza/geosafe/pull/388 . I think it's better to just remove the close button in the footer and let the close mark in the header as it is.
