### ISSUE TITLE
Improve report download buttons layout and text

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#224]
- [x] space missing between `keep` and the `Close` button
- [x] use `Save Report` or `Save Results` instead of `Keep`?
- [x] make it more clear that `Download Report` provides a bundle of the map + table
- [ ] add an option to allow downloading of impacted features (actual data)?

![screen shot 2017-09-12 at 10 16 52](https://user-images.githubusercontent.com/10201533/30315262-a05377f2-97a3-11e7-8861-3bb057f00cb5.jpg)

**Comment by boney-bun** [comment]
hi @cgiovando
below is the screenshot based on your request:
![Screen Shot 2017-09-24 at 2.12.19 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6456f76b7191a37af113294f5e565edd3c4a4356bcbbd671f3e57862804e0ee5806f0b7c906945aded874abf54e8208b49d1b1e88e49d2f42f67b6d5db1063474f4dcbed5727a29841c95df64de04451a11a3f6ae7752431.png)

could you elaborate more on the last two points?
- `Download Report` is changed to `Download Impact & Table reports`.
- `Download Impact Layer` is added, but not sure which *impacted features* are you referring to.

Let me know if this suit your expectation.

**Comment by boney-bun** [comment]
hi @gubuntu @cgiovando. 
i’m thinking of `Download Impact Layer`. 
What should we return on this link:
* the thumbnail
* the full image
* or, probably QGS or QLR file?

**Comment by gubuntu** [comment]
Link to the layer download page popup so the user can choose
