### ISSUE TITLE
Improve rendering of results on main map

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#225]
- [x] colors are clashing (yellow on yellow, etc)
   - that's a data manage / styling issue (not GeoSAFE)
- [x] allow reordering of layers or put exposure on top
  - a layer switcher button has been implemented for a while now
- [x] add scroll bar to layer list/legend
  - implemented (just wasn't in production when you tested)
- [ ] allow users to remove impact result layer from map
  - will be done by #214
- [ ] don't prompt users to run a new analysis every time the map is moved/zoomed
- [x] require users to include units and class labels for input layers
  - not easy to enforce in GeoNode. Again, a data managment  / styling issue. 

![screen shot 2017-09-12 at 10 23 59](https://user-images.githubusercontent.com/10201533/30315687-1b0ccb96-97a5-11e7-83ed-b9c897da7a63.jpg)

**Comment by gubuntu** [comment]
@boney-bun in this ticket just do the second-last item
