### ISSUE TITLE
Pressing rerun analysis gives an ugly error page

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#231]
Trying with the earthquake Nepal scenario here:

http://geonode.kartoza.com/geosafe/analysis/

![licecap](https://user-images.githubusercontent.com/178003/30626800-78f6e88e-9df6-11e7-9b3f-6ac00993b7d1.gif)

Please make it just give a nice feedback saying the analysis has been restarted.

**Comment by boney-bun** [comment]
i couldn't replicate the issue on my local and staging.
This is on my local:
![geosafe 231](https://user-images.githubusercontent.com/4602383/31068212-391573b8-a781-11e7-94f7-eff391c6773d.gif)
The same thing happened on staging:
![geosafe 231-part2](https://user-images.githubusercontent.com/4602383/31068289-8a5d18e8-a781-11e7-9421-cf5d14fa4940.gif)

would you like an additional message after pressing the `Rerun Analysis` button @timlinux ?

**Comment by gubuntu** [comment]
please check and comment or close

**Comment by NyakudyaA** [comment]
I have checked and all analysis are completing properly even the full extent analysis. 
There is no longer an option to rerun a completed analysis but it only applies to the failed analysis which would need to be run. So for now I will close as all analysis are completing
