### ISSUE TITLE
Fix download UI

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#233]
- [ ] qlr layer name must have the same name as the geonode layer, not a random string
- [ ] change 'QGIS Layer file' to 'QGIS layer file (.qlr)
- [ ] change 'QGS Layer file' to 'QGIS project file (.qgs)

and where are the embed widget and other new download options?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/496911/30638288-223e2834-9e25-11e7-83ad-55b9c4dec1ae.png">

**Comment by boney-bun** [comment]
this issue is addressed on kartoza/geonode#337

**Comment by gubuntu** [comment]
you shouldn't need to manually link the PR as above, it should be automatic if you comment it correctly.

Once it's merged and deployed, move to Testing in waffle - this procedure now applies to all development

**Comment by gubuntu** [comment]
Don't close before live testing (so move back to Testing)
