### ISSUE TITLE
add keywords to GeoSAFE layer metadata

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#237]
# Issue

Having multiple layers 'polluting' the GeoNode layer list makes it hard to distinguish curated layers from analysis results from random public contributions or test layers. 

GeoNode uses ISO metadata keywords to contruct the keyword menu in the Layer UI, so let's use this to organise layers. 

# proposed solution

- [ ] programatically add 'GeoSAFE Impact Layer' to the metadata keywords as part of its publication process after an analysis. 
- [ ] programmatically add 'GeoSAFE Exposure Layer' or 'GeoSAFE Hazard Layer' to the ISO metadata for all layers on a routine or event basis, be parsing the InaSAFE keywords (and checking that it's not already in the ISO keyword field)
- [ ] programatically add 'GeoSAFE Aggregation Layer' in the same way

**Comment by NyakudyaA** [comment]
I have added the filters manually for now. It seems all the new analysis layers are currently being assigned keywords `Human Health and Safety`

![screenshot 2018-11-06 at 12 17 27](https://user-images.githubusercontent.com/2510900/48057946-f331dd00-e1bd-11e8-9c77-716593f088fb.png)

**Comment by NyakudyaA** [comment]
> # Issue
> Having multiple layers 'polluting' the GeoNode layer list makes it hard to distinguish curated layers from analysis results from random public contributions or test layers.
> 
> GeoNode uses ISO metadata keywords to contruct the keyword menu in the Layer UI, so let's use this to organise layers.
> 
> # proposed solution
> * [ ]  programatically add 'GeoSAFE Impact Layer' to the metadata keywords as part of its publication process after an analysis.
> * [ ]  programmatically add 'GeoSAFE Exposure Layer' or 'GeoSAFE Hazard Layer' to the ISO metadata for all layers on a routine or event basis, be parsing the InaSAFE keywords (and checking that it's not already in the ISO keyword field)

This falls into the category of metadata handling. Currently, InaSAFE designates all metadata as `Human health` So before uploading a user needs to change that keywords to the respective ones available in Geonode already. 
> * [ ]  programatically add 'GeoSAFE Aggregation Layer' in the same way

Same as above as it is a metadata issue rather than doing in programmatically. If InaSAFE generates metadata that has proper keywords then those keywords will appear in GeoNode

**Comment by gubuntu** [comment]
nice manual solution @NyakudyaA 

but it's still a programmatic solution if you want InaSAFE to do it (which isn't going to happen until there's further development with InaSAFE)

**Comment by NyakudyaA** [comment]
This is working properly and we only have to update the metadata for analysis result so that it can be Impact Analysis. 

I will close this ticket for now as we can edit the metadata to do what we need it to do.
