### ISSUE TITLE
add user and group to GeoSAFE layer filter

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#242]
# Issue

GeoSAFE currently ignores GeoNode authentication and lists all valid InaSAFE layers, no matter who has permission to see them

# Proposed solution

1. See how decorators are used on layer views and add the same decorators to the GeoSAFE fetch-layer views
1. In the GeoSAFE layer filter, add a filter for  the current user

see with #327

**Comment by NyakudyaA** [comment]
see comment in https://github.com/kartoza/geosafe/issues/327
