### ISSUE TITLE
Reorganize a bit the UI for the Impact and Report section

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#261]
_From @vdeparday on May 31, 2016 11:19_

![image](https://cloud.githubusercontent.com/assets/1036189/15672577/1a5113be-274f-11e6-9c51-ea91d38ca02f.png)

I am not sure exactly what the right answer is but I feel like the impact part should at least be below the "Run" part as they are a result of running the impact modelling. 

Maybe the same with go to Analysis list or maybe they can stay in that order but need to be a bit better organized and clearer to the user.

Maybe having one category "Calculate Impacts" only with the impact function and then we could add configuration icons in there.
And then below something with Results with the current and previous results.

It would be great if we can come with something clearer on paper/mockup and then we can make the simple update. 

_Copied from original issue: kartoza/geonode#77_

**Comment by gubuntu** [comment]
_From @timlinux on May 31, 2016 19:18_

> I am not sure exactly what the right answer is but I feel like the impact part should at least be below the "Run" part as they are a result of running the impact modelling.

Yes that makes sense. Perhaps later we can find some kind of contextual switch between 'Impact view' and 'analysis preparation view', but for now just swapping them around would be good.

> Maybe the same with go to Analysis list or maybe they can stay in that order but need to be a bit better organized and clearer to the user.

OK

> Maybe having one category "Calculate Impacts" only with the impact function and then we could add configuration icons in there.
> And then below something with Results with the current and previous results.

Perhaps Impact function + Run button could go in the 'Calculate Impacts' section.

> It would be great if we can come with something clearer on paper/mockup and then we can make the simple update.

OK @lucernae can you take on a task of getting a mockup prepared for our meeting next tuesday with @vdeparday ?

# CC

@Gustry 
@lucernae 
@ismailsunni

**Comment by carina1000** [comment]
"Perhaps later we can find some kind of contextual switch between 'Impact view' and 'analysis preparation view'"

@gubuntu can you please explain this a bit more I'm not sure I understand. So currently we depict the 'impact view'. What is the function of the 'analysis preparation view'?

**Comment by gubuntu** [comment]
actually this is redundant with the GeoSAFE 4 upgrade
