### ISSUE TITLE
Long running process stalls on geonode.kartoza.com

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#268]
_From @timlinux on September 21, 2016 17:53_

Hi @lucernae 

@vdeparday has reported that trying to do a full analysis is timing out. I can see in the analysis list there are a bunch of pending jobs. Can you check if celery is running or what is going on? See screenshot below. Please treat this as urgent as @vdeparday is trying to demo it to people and we need it to be bullet proof....

![screen shot 2016-09-21 at 7 51 46 pm](https://cloud.githubusercontent.com/assets/178003/18722406/058320be-8035-11e6-8b27-4975b5cbe6fd.png)

_Copied from original issue: kartoza/geonode#122_

**Comment by gubuntu** [comment]
_From @lucernae on September 22, 2016 10:41_

It takes too long for polygon flood on roads to complete, so it blocks other tasks.
I will try to find a workaround.

**Comment by gubuntu** [comment]
_From @lucernae on September 22, 2016 16:13_

Solve this by:
- Running 4 celery workers to process as many concurrent process as possible
- Disable tasks prefetching using Celery config:
  
  ```
  CELERY_ACKS_LATE = True
  CELERYD_PREFETCH_MULTIPLIER = 1
  ```
- Disable tasks prefetching using celery worker optimization flag (-Ofair):
  
  ```
  xvfb-run -a --server-args="-screen 0, 1024x768x24" celery -A headless.celery_app worker -Q inasafe-headless -l info -Ofair
  ```
- Will document this for Hendrik.

**Comment by gubuntu** [comment]
_From @timlinux on September 22, 2016 20:9_

Hi @lucernae 

I tested it with roads on RW poles and it seemed to generate the result, but I had to reload the analysis view and then manually select the impact layer in order to see the result. Can you check on that?

**Comment by gubuntu** [comment]
_From @timlinux on September 22, 2016 20:10_

And thanks for the fixes so far by the way!

**Comment by gubuntu** [comment]
@NyakudyaA please test and comment (on testing and INGC instead of the OP host)

**Comment by NyakudyaA** [comment]
I ran a full analysis on testing and Mozambique and all the processes ran properly. They did not crash and the site was still usable during the process.
