### ISSUE TITLE
 Rasters do not stay visible in geosafe layer extent

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#271]
_From @NyakudyaA on December 20, 2016 11:23_

# Problem

When trying to use a population raster in analysis it results in the layer appearing and then disappearing quickly.

Geosafe recognizes that the layer has correct keywords and is a population layer but is unusable in running analysis

![qgis](https://cloud.githubusercontent.com/assets/2510900/21050319/a94a2622-be22-11e6-973f-905f20a966a3.gif)

Data: `inasafe/test/data/hazard/tsunami_wgs84.tif`

![out](https://cloud.githubusercontent.com/assets/2510900/21421452/976c36b6-c83b-11e6-8135-b2c3af0d44b7.gif)

Analysis can then not be done.

# Solution 

Allow layer to stay visible so that analysis can be carried out.

_Copied from original issue: kartoza/geonode#126_

**Comment by gubuntu** [comment]
@NyakudyaA is this still the case on testing?

**Comment by NyakudyaA** [comment]
This is now working on the testing server.
