### ISSUE TITLE
Upload error when running concurent processes. A process in geosafe and upload of layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#272]
_From @NyakudyaA on December 20, 2016 11:37_

# Problem

When trying to upload a layer in geonode whilst running analysis using a big layer causes an upload error.

![upload](https://cloud.githubusercontent.com/assets/2510900/21042882/ece1aab6-bdfc-11e6-91bb-55182a7d88a9.png)

# Solution

Fix upload.

N.B - There is a current analysis running in another geosafe tab. 
* Hazard Layer - geonode:nsunga_tanzania
* Impact Layer - geonode:osm_buildings_current_tanzania

_Copied from original issue: kartoza/geonode#129_

**Comment by NyakudyaA** [comment]
I have tested this and this seems to be fine. This is more related to the server resources. If the server is relatively small and a user is running a process that is resource heavy it is expected that other processes will be slowed down. Tried uploading whilst a current process was running and the uploads worked.
