### ISSUE TITLE
Preview of  analysis list  is broken whilst running geosafe analysis (in create analysis page)

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#274]
_From @NyakudyaA on December 20, 2016 12:10_

# Problem

I have  analysis running another tab and when I open another instance of geosafe in a different tab. I cannot get the analysis list.
![analysis](https://cloud.githubusercontent.com/assets/2510900/21041359/2c0eab6c-bdf3-11e6-92d2-5a34cac06d8e.png)

# Solution

Fix and let the user see the analysis list. 
Give nice error codes. Do not run geonode in debug mode on production.

_Copied from original issue: kartoza/geonode#131_

**Comment by NyakudyaA** [comment]
This is still an issue. 
Example of analysis running
![list](https://user-images.githubusercontent.com/2510900/45296292-dfd9fc80-b501-11e8-981a-a909629f6016.png)

And trying to view the analysis list
![analysis-list](https://user-images.githubusercontent.com/2510900/45296308-ec5e5500-b501-11e8-9ad1-4af1bc036980.png)

**Comment by lucernae** [comment]
Should have been fixed now.

**Comment by NyakudyaA** [comment]
This is working now. will close this
