### ISSUE TITLE
show analysis results in empty tables and reports after running analysis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#278]
_From @NyakudyaA on December 22, 2016 11:32_

# Problem

After running an analysis I click on show analysis summary:

Earthquakes on buildings

Data:
* Exposure: `inasafe/safe/test/data/exposure/buildings.shp`
* Hazard: `inasafe/safe/test/data/hazard/classified_generic_polygon.shp`

![analysis_resu](https://cloud.githubusercontent.com/assets/2510900/21423621/bd11bf84-c846-11e6-821c-7bfe2dd837bb.png)

Then clicking on show map report and show table report all result in black outputs:

![impact_report](https://cloud.githubusercontent.com/assets/2510900/21423655/e4c38274-c846-11e6-8b58-816363abaf70.png)
![report](https://cloud.githubusercontent.com/assets/2510900/21423656/e4c6d1fe-c846-11e6-91c6-50ea99fabfe2.png)

# Solution

All results should be visible

_Copied from original issue: kartoza/geonode#138_

**Comment by gubuntu** [comment]
test again after InaSAFE 4 upgrade

**Comment by myarjunar** [comment]
I made an alternative to this issue on #360. Because iframe does not work so I propose to open the report on a new tab instead of on a modal view.
