### ISSUE TITLE
Report map does not show complete words after running analysis in geosafe

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#279]
_From @NyakudyaA on December 23, 2016 10:48_

# Problem 
After running analysis the reports that are generated do not show complete words for all items highlighted.

![version](https://cloud.githubusercontent.com/assets/2510900/21452200/fa8d92ee-c90d-11e6-9b06-79f40c11c2ce.png)

# Solution

Fix to show Inasafe version

_Copied from original issue: kartoza/geonode#140_

**Comment by gubuntu** [comment]
test again after InaSAFE 4 upgrade

**Comment by myarjunar** [comment]
Fixed on InaSAFE 4 (it still depends on the template though)

**Comment by NyakudyaA** [comment]
I have tested this and the map shows all the words.
![screenshot 2018-10-09 at 13 43 11](https://user-images.githubusercontent.com/2510900/46667241-56355180-cbc9-11e8-83d2-9d8467ad1e0e.png)
