### ISSUE TITLE
Changing layer order hides one layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#282]
_From @timlinux on September 24, 2017 6:56_

When I toggle layer order, one always gets hidden....

![licecap](https://user-images.githubusercontent.com/178003/30780209-0285ac98-a130-11e7-8fe8-ac742450c27e.gif)

_Copied from original issue: kartoza/geonode#342_

**Comment by gubuntu** [comment]
_From @NyakudyaA on September 24, 2017 10:24_

Confirmed this as well. This typically occurs when the layers involved are raster

**Comment by gubuntu** [comment]
@NyakudyaA is this still the case (try on the testing server)

**Comment by NyakudyaA** [comment]
I have tried this on the testing server and this is still the case. Tested with the earthquake in Padang 2009 layer and the buildings

**Comment by boney-bun** [comment]
@NyakudyaA i found no problem in the testing.
tested using earthquake in padang 2009 and buildings-test layers.

![geosafe 282](https://user-images.githubusercontent.com/4602383/46457366-43dba200-c7dc-11e8-8e05-245d97ff8b40.gif)
