### ISSUE TITLE
Layers are not getting loaded

### ISSUE THREAD

**Issue by saravanaganesh18** [kartoza/geosafe#283]
I've uploaded two sample layers (**_Padang_EQ, Padang_Buildings_**) to geonode.kartoza and the analysis part is working fine and reports are generated without any issues (Created the keywords in InaSafe and converted the metadata to 3.5).

![image](https://user-images.githubusercontent.com/37054331/36986067-e59d99ce-20be-11e8-8cf9-ee6f2029cdb6.png)

But if i upload the same layers to our server, which we have installed by y'day the layers are not even getting listed in the "GeoSafe -> Create Analysis" page. I am a non-technical person and one of my friends helped me with the installation/hosting (https://github.com/kartoza/kartoza-rancher-catalogue/issues/16). How to make sure the installtion process is correct or not ? Do we have to install any additional package ? We are working in **_GeoSAFE based on GeoNode with QGIS Backend_**. Any advise or guidance would be greatly appreciated.

1) Uploaded layers
![image](https://user-images.githubusercontent.com/37054331/36987158-b60c8b18-20c1-11e8-8166-c79fe983651d.png)

2) Rancher Stacks
![image](https://user-images.githubusercontent.com/37054331/36987386-2aa57408-20c2-11e8-9b0a-8378b357e9ad.png)

**Comment by timlinux** [comment]
You need to make sure that you upload the .xml file with the layers so that their keywords are registered. Also I suggest to upload the .qml files for the layers so they are styled nicely.

**Comment by dacodekid** [comment]
@timlinux 

These are the files @saravanaganesh18 uploaded into http://geonode.kartoza.com/geosafe/analysis/create  (which works fine), but not showing in our installations.

![image](https://user-images.githubusercontent.com/10047844/37025595-2593e6ce-20fa-11e8-891f-193694e081f1.png)

**Comment by dacodekid** [comment]
@timlinux @saravanaganesh18  - Attached sample files.

[For_GeoSAFE.zip](https://github.com/kartoza/geosafe/files/1785007/For_GeoSAFE.zip)

**Comment by timlinux** [comment]
Are you able to share a link to the running instance and the rancher admin panel?

**Comment by dacodekid** [comment]
@timlinux  http://159.65.248.35:8080/

**Comment by saravanaganesh18** [comment]
This issue has been resolved. The problem is with the Metadata (Django Administration). Purpose and Category were empty for all the layers uploaded. I was updating the keywords and category only through "Edit Metadata" option, which eventually didn't work. Don't know why it didn't get updated automatically. Any way, will raise that as a separate issue.

![4](https://user-images.githubusercontent.com/37054331/37255387-ce4bc90a-2571-11e8-9a44-b4ce2117b1c1.png)
