### ISSUE TITLE
UI/UX review

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#289]
We need a fresh review of the GeoSAFE UI/UX

including a `cognitive walkthrough`

I wil also be evaluating user experiences on my site visit to Maputo at the end of May.

child of #306

**Comment by myarjunar** [comment]
notes from last meetin gwith @carina1000 :

- `try it out` button at the bottom of the landing page
- `try it out` button should be aligned with the text underneath
- search for data - what data ?
- advanced search only redirect to the layers list page
- [ ] about option in the topbar should be something to describe the app
- landing page, should we redirect to the create analysis page ?
- analysis list only available from geonode page (#317)
- default extent is the extent of available layers
- aggregation is optional (make the run button enable after only selecting hazard and exposure)

@carina1000  we've got geosafe working now on http://testing.geonode.kartoza.com

**Comment by carina1000** [comment]
I've handed this ticket over to you @myarjunar  for implementation!

**Comment by gubuntu** [comment]
@myarjunar yes please implement the above, but @carina1000 please plan a more thorough UI/UX review as per the OP, including re-assessing UI-related issues in the backlog.

**Comment by myarjunar** [comment]
I think most of the points will be related to this ticket https://github.com/kartoza/geonode/issues/420 . I've done some of this related to analysis capabilities

**Comment by gubuntu** [comment]
https://github.com/kartoza/geonode/issues/420 is about GeoNode

This ticket is about GeoSAFE

**Comment by myarjunar** [comment]
first 6 points are coming from landing page which means related to INGC Geonode skin which is changes on geonode CMIIW. I'm only working at what I could change on geosafe repo at the moment

**Comment by gubuntu** [comment]
I think there's just one item not done, I made a checkbox. Will you still do it? If not pull it into a separate issue in backlog and then close this

**Comment by myarjunar** [comment]
> about option in the topbar should be something to describe the app

@gubuntu could you give me more details on this?

**Comment by gubuntu** [comment]
I think a flat page linked to an additional GeoSAFE menu item: 'About' where we can add some documentation and links to other docs.

**Comment by NyakudyaA** [comment]
@myarjunar I think this is still missing. There is no about page describing GeoSAFE. The only about page on the site describes Geonode. I have opened a new ticket with this issues and will close this one
