### ISSUE TITLE
Do GeoSAFE PT translation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#292]
translate GeoSAFE UI strings in transifex 

depends on #291

**Comment by boney-bun** [comment]
Hi @raisserafael

@lucernae has made a GeoSAFE project in transifex.
please go to https://www.transifex.com/inasafe/geosafe/dashboard/ for translating GeoSAFE.
this assumes that you already have an account on the site.

please let me know if you have done with the translation as i will need to add the latest to the repo.

**Comment by myarjunar** [comment]
nice stuff, @raisserafael we need to translate InaSAFE core code as well as already created here https://www.transifex.com/inasafe/inasafe-code/ . It will translate the report generated by GeoSAFE into Portuguese.

**Comment by gubuntu** [comment]
That's in #299 @myarjunar.

**Comment by boney-bun** [comment]
hi @raisserafael 

since we have moved the INGC theme into the new repo, then the translation for the landing page is now in https://www.transifex.com/inasafe/geosafe/ingc/

**Comment by lucernae** [comment]
Thanks @boney-bun .
CC @gubuntu we put the translation project into GeoSAFE's transifex project for now but it's on a separate resource than geosafe.

**Comment by gubuntu** [comment]
as long as it all gets translated (Landing page, analysis page, etc.) and deployed that's fine

**Comment by gubuntu** [comment]
@lucernae I've translated and reviewed most of the strings in geosafe/ingc so please go ahead and use them. 

There are a few phrases where the English has been chopped up e.g. phrase 9 does not follow phrase 8 properly
1. the first set of unreviewed strings make up the fully translated paragraph from #420, so you could fix the English and apply the translation.
1. The last string is not complete, or some words or lines are missing at the end.

**Comment by lucernae** [comment]
I only handled the infra part. I will let @boney-bun handle the details.
@boney-bun can you take over from here?

**Comment by boney-bun** [comment]
@lucernae let me handle this. thanks

**Comment by gubuntu** [comment]
@boney-bun line 24 in transifex english needs fixing:

Change `Why not creating one?` to `Why not create one?`

**Comment by gubuntu** [comment]
this done @boney-bun ?

There are still lots of strings in the GeoSAFE UI that don't even seem to be on transifex - pls work with @myarjunar to get them there so I can translate and we can deploy - in #400

**Comment by gubuntu** [comment]
I've just translated the rest of the geosafe/django resource. I had completed the ingc resource last week but did not realise I had to do django too. I hope you can just use it and deploy! cc @myarjunar

**Comment by gubuntu** [comment]
@raisserafael please review the portuguese through the site (GeoNode and GeoSAFE) and fix any errors in Transifex or notify us of any additional strings that need to be added to Transifex to translate
