### ISSUE TITLE
notify user by email when analysis is complete

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#297]
- [ ] and let them know they will be notified

consider implementing #264 to achieve this

also see #275

**Comment by myarjunar** [comment]
has #264 been implemented?

**Comment by gubuntu** [comment]
no it hasn't - but it looks like @lucernae wants to do since he opened #383 recently

**Comment by gubuntu** [comment]
I got an email! 

- still need to put some text somewhere letting the user know they will get an email

- and the link in the email was invalid  - `x-webdoc://E685DA33-2010-4905-806E-064A6C1EE0BA/geosafe/analysis/create/151`

**Comment by lucernae** [comment]
Lol, @myarjunar It's supposed to be `SITEURL` not `SITE_URL` without underscore 😉.
Anyway, nice to see that it works.

**Comment by NyakudyaA** [comment]
The URL that is being published is now correct.

**Comment by gubuntu** [comment]
> and let them know they will be notified

Add a line to the message box that appears after the analysis has started to inform the user that they will get an email once it is done., even if it takes several hours.
