### ISSUE TITLE
Translate InaSAFE reports to PT

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#299]
translate InaSAFE reports to PT

Option 1: here is the help text if you want to change it using the dialog
![Selection_230.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db9196268197a080e78011f70db2d86b56357c2301a03f32dfa17de743290557091af8400d5a11fcacdb2ba6b06877de580effcd7f1d2598694ef1e1c84afd13b0328a478fb7b98844c1ec3f21ef8c8c4b390c48.png)

Option 2: the only proper way to do it is a full translation of InaSAFE desktop in https://www.transifex.com/inasafe/inasafe-code/
(the problem is that many of the report strings in the summary table etc are pulled from definitions)

Option 3: as a work around you could use only numeric data from the analysis results and
then create your own templates and override the templates in the codebase. Find the templates in `https://github.com/inasafe/inasafe/tree/develop/safe/resources/qgis-composer-templates` 

  - in the meantime start translating standard report strings in your own docs

**Comment by gubuntu** [comment]
@raisserafael please upload the documents you have translated already
and please follow up with your transifex requests to join PT translation groups for GeoNode and InaSAFE.
[Pop_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46d89b8a1c9682ab83ecfd0fe64de29b234324676b5ee17e2884b12ce7447f055e0a4bf9410d0d44fcffdd2cf2b23962964e49bc8f3900299f7744eeaa880dbe09b0218e4c83b3b48d4fc2eb3d27e499c2.pdf)
[Pop_table.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46d89b8a1c9682ab83ecfd0fe64de29b234324676b5ee17e2884b12ce7447f055e0a4bf9410d0d44fcffdd2cf2b23962964e49bc8f3900299f7744eeaa880dbe06b0218e4c83b3b48d4fc2ea3422e599c2.docx)
[Structure_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db8088368197bc9dec8057a55ffc916b0a65633b0ba92e7391a172fd1723005d0b46fa150c5e11f9ac897ef4b63c76de5b5fe9d47f4366846c4ff8e7df46f554f832815d87b7b68b49c3ee382de0888d4d37160d0ac4.pdf)
[Structure_table.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db8088368197bc9dec8057a55ffc916b0a65633b0ba92e7391a172fd1723005d0b46fa150c5e11f9ac897ef4b63c76de5b5fe9d47f4366846c4ff8e7df46f554f832815d84beb68b49c3ee382de0888d4c3e1d060ac4.docx)
[Roads_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46da9b9b2791bcbd8eebb346e611b2843b492d762a10e17132d0bb29ed4623070b0b4ff9440d5f11aef9892df2b168748f4e17ff933c0120996048e6edc00db513bb28814e80b5ba8f44c7eb3f26e789875d73.pdf)
[Roads_table.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46da9b9b2791bcbd8eebb346e611b2843b492d762a10e17132d0bb29ed4623070b0b4ff9440d5f11aef9892df2b168748f4e17ff933c0120996048e6edc00db513bb27814e80b5ba8f44c7eb3f27ee83865d73.docx)

**Comment by gubuntu** [comment]
@myarjunar please can you apply the text that @raisserafael translated in the above documents in https://www.transifex.com/inasafe/inasafe-code/

**Comment by myarjunar** [comment]
I can, but it wouldn't be perfect. Also if we only translate the strings that appear in the above documents, we might be getting mixed language since the report is very dynamic. The best way to do it is by translating all the strings in transifex. 

Some strings in the above documents also not relevant with InaSAFE v4.

**Comment by gubuntu** [comment]
@myarjunar can you then specify which section @raisserafael must transate in transifex? Or are you saying the whole of InaSAFE? (there's not time for the latter)

I still think it's better for you to apply what @raisserafael has done so at least it is live in production and can be improved later.

**Comment by myarjunar** [comment]
@gubuntu I hope we put some kind of tag on the strings in transifex but we didn't, so it would be really hard to find which one is for reporting. Yes, for now I just put every text in the translated report into transifex.

**Comment by gubuntu** [comment]
thanks @myarjunar, let's get those deployed asap. 

@raisserafael please go into the inasafe-code transifex project and translate as many other strings as you can, as soon as you can and also check on your reporting translations that Rohmat has already entered in transifex

**Comment by gubuntu** [comment]
@myarjunar I've reviewed the strings on https://www.transifex.com/inasafe/inasafe-code/ so you can go ahead and use them. 

What happens with %s string replacement? where does the PT word come from for the %s?

**Comment by myarjunar** [comment]
@gubuntu we just let `%s` as it is. InaSAFE will replace it with desired string on runtime.

**Comment by gubuntu** [comment]
yes but how do we ensure that the replacement string is also translated? I guess it will be one of the strings from inasafe-code on transifex, right? So we should test and see if they get replaced with EN or PT words.

**Comment by gubuntu** [comment]
I'm still getting English reports at INGC. Is the InaSAFE not picking up the language override (I'm not in PT locale but I selected PT in GeoNode)

**Comment by myarjunar** [comment]
@gubuntu the main issue #300 is still in review. bear in mind that if InaSAFE's transifex is not completely translated into PT, we might have mixed language on the report.

**Comment by gubuntu** [comment]
at least if we have mixed language we know the locale switch is working with the strings that have been translated and it will help identify which other specific strings still need translating.

**Comment by gubuntu** [comment]
@raisserafael please test and review in production

**Comment by gubuntu** [comment]
I switched to PT but get an English report

[gavin flood on minplants_table.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46ef958c2a8cc3af83e6b047e452fed4244f29632505ad3f63baf729bd4e7e43434d0eee1e020a17b8eb8339a3be6d72de545db9856c0a71933d44feb88219eb06ee248e5d99a4fedb1294b7607caddecd5d340c041083fe5831a1994cc85df542e44551b65e.pdf)

**Comment by myarjunar** [comment]
@gubuntu that is because we still don't have the translation from InaSAFE core. I'm gonna hardcode the text in the template rather than using the expression from InaSAFE.

**Comment by gubuntu** [comment]
ah OK, I would have translated them in core transife if I had known (or you could have using my translations above)

**Comment by myarjunar** [comment]
that's fine. since the template is specific only for INGC and also has its own repo, it's better to write the text straight on the template I guess.
