### ISSUE TITLE
GeoSAFE Papercut fixes

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#30]
- [x] Add filtered/unfiltered label above hazard/exposure
- [x] Add zoom out control
- [x] Put icon of hazard/exposure menu from InaSAFE Resources
- [ ] Put icon of hazard/exposure menu from Maria
- [x] Automatically show infographic report when loading completed analysis
- [x] Add User defined title in the form (to give title to analysis impact layer)
- [x] Update styles for toggle switch for save button
- [x] Add label in analysis confirmation dialog for the save button to explain what it do
- [x] Rearrange buttons for report and impact function run (But it is also possible it doesn't fit with smaller screen
- [x] Add button link to Download Layer and Geonode layer detail page
- [x] Update Analysis List view to provide link to specific analysis result page.

**Comment by gubuntu** [comment]
@lucernae please complete and close

**Comment by lucernae** [comment]
We skip this:
> Put icon of hazard/exposure menu from Maria

We take the icons from InaSAFE resources.
