### ISSUE TITLE
Change geosafe default view to max extent of valid layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#301]
# Problem
When you enter the GeoSAFE analysis screen, the default view is the whole world, even if the available data sets cover only a small part. 

e.g. the INGC view should go straight to Mozambique

# Solution
Get the total extent of all valid and avaiable GeoSAFE layers and choose a centre and zoom level based on that.

The 'zoom to global view' control shoud actually do the same thing and be renamed 'zoom to full extent', like the standard GIS tool to 'zoom to full extent of all layers' rather than 'the whole world'

**Comment by lucernae** [comment]
Note for @boney-bun :

This might be too expensive to count where there are so many layers.

I had an alternative. CMIIW @boney-bun you made a marker group for the map for all layers. We can just zoom to the bounds of that marker group in the leaflet client.

I was thinking something like this:
https://stackoverflow.com/questions/16845614/zoom-to-fit-all-markers-in-mapbox-or-leaflet
