### ISSUE TITLE
hazard layer not rendering properly in report

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#310]
Only half the flood layer draws in the report

(feedback from INGC site visit)

**Comment by myarjunar** [comment]
can we close this? seems like it's no longer relevant after InaSAFE v4. only impact layer is drawn on the map report.

**Comment by gubuntu** [comment]
that's true but we want the hazard and aggregation layers there too... https://github.com/kartoza/geosafe/issues/385

But I'll close it since that's not implemented yet
