### ISSUE TITLE
Legend doesn’t fit on the screen

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#314]
(INGC feedback)

**Comment by lucernae** [comment]
@gubuntu Is this still relevant? Do you have some screenshot for us to look into?

**Comment by gubuntu** [comment]
very much so. In this example half the exposure legend is cut off and the impact layer legend is completely off screen. I think we just need to add scroll bars when it reaches screen limits. 
![screenshot 2018-11-12 at 10 29 52](https://user-images.githubusercontent.com/496911/48335359-24028e00-e666-11e8-91eb-c4a989286e28.png)
