### ISSUE TITLE
Add cyclone to GeoSAFE

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#319]
it is in InaSAFE so should not be much work

**Comment by gubuntu** [comment]
@raisserafael have you added keywords to the cyclone layers? They are not appearing as valid hazard layers in GeoSAFE

**Comment by gubuntu** [comment]
InaSAFE needs polygon cyclone hazard zones, not cyclone track points.

**Comment by gubuntu** [comment]
- style in  qgis and upload new styles
- add InaSAFE keywords so they are usable in GeoSAFE

@NyakudyaA can help

**Comment by NyakudyaA** [comment]
@raisserafael is going to style them. It seems that cyclones are not supported in GeoSAFE but are available in InaSAFE desktop so they will not be usable as a hazard but will only be available as context layer

**Comment by gubuntu** [comment]
> It seems that cyclones are not supported in GeoSAFE
what leads you to say that? Is it just missing a front-end icon? @myarjunar?

**Comment by NyakudyaA** [comment]
> It seems that cyclones are not supported in GeoSAFE
> what leads you to say that? Is it just missing a front-end icon? @myarjunar?

There are only `Floods,Tsunami,Earthquake,volcano and volcanic ash` @myarjunar if you confirm that GeoSAFE does not support cyclones then we can close this and leave the layer configured as Geonode layer

**Comment by myarjunar** [comment]
@gubuntu @NyakudyaA InaSAFE 4 already supports cyclone hazard so we can add it. the only thing missing is the cyclone icon.

**Comment by gubuntu** [comment]
Please go ahead

**Comment by NyakudyaA** [comment]
@myarjunar 
The cyclone icon does not appear in testing and the appearance is not very nice.
![cyclone-icon](https://user-images.githubusercontent.com/2510900/48488091-a5098300-e828-11e8-920c-4a61c2bb8cb9.png)

**Comment by myarjunar** [comment]
@NyakudyaA it only a matter of reloading static files on testing site. will do it shortly

**Comment by boney-bun** [comment]
@NyakudyaA the cyclone icon should appear correctly now

**Comment by NyakudyaA** [comment]
Awesome @boney-bun
