### ISSUE TITLE
check INGC Worldpop layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#326]
Jose’s worldpop data doesn’t seem right - lots of very small value cells where he thinks there is high density population. 

(Maputo site visit feedback)

**Comment by gubuntu** [comment]
@NyakudyaA please check this and also why it's not appearing as an exposure layer in GeoSAFE

**Comment by NyakudyaA** [comment]
I am investigating why it doesn't appear as valid exposure layer. The keywords seem to be fine if you download the layer as xml. Will test again when GeoSAFE has been upgraded

**Comment by gubuntu** [comment]
Please check again @NyakudyaA

**Comment by NyakudyaA** [comment]
I have fixed this layer. will check other population layers
![screenshot 2018-10-17 at 18 19 56](https://user-images.githubusercontent.com/2510900/47101055-5375d480-d239-11e8-8312-b3437ff20c88.png)
