### ISSUE TITLE
show version 4 report

### ISSUE THREAD

**Issue by myarjunar** [kartoza/geosafe#335]
child of #53
child of #58
- [x] generate report as the analysis is finished
- [x] update geosafe report template
- [ ] upload pdf report and linked it with the impact layer and the analysis object (moved out to #402)

**Comment by gubuntu** [comment]
only partly resolved with #342

**Comment by gubuntu** [comment]
@myarjunar will you be doing the last item in the OP? 

If not please move it into a new issue in the backlog then you can close this
