### ISSUE TITLE
map thumbnails not being created

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#36]
I created a map 'gavin test' and it has not thumbnail on http://geosafe.kartoza.com/maps/?limit=100&offset=0

Also, in that map (http://geosafe.kartoza.com/maps/86), while OpenMapSurfer Roads rendered yesterday, they are not rendering today. 

Also, one of the overlay layers does not draw. If it's because it is a different extent, there should at least be the ability to 'zoom to layer extent'.

**Comment by Gustry** [comment]
Thanks @gubuntu for the report. Maybe it's better to use the qgis app repo for tickets related to Geonode + QGIS : https://github.com/kartoza/geonode_qgis_server. This repo is specific to geosafe.

**Comment by gubuntu** [comment]
transferred to https://github.com/kartoza/geonode_qgis_server/issues/9
