### ISSUE TITLE
Report template uploader

### ISSUE THREAD

**Issue by myarjunar** [kartoza/geosafe#363]
child of #58

- create page for uploading template (map/table)
- use custom template for generating report if available

**Comment by gubuntu** [comment]
haven't you just implemented this @myarjunar ? please update waffle status

**Comment by myarjunar** [comment]
not yet, I think this is low priority. Currently we enforce the custom template to be retrieved from custom theme repo.

**Comment by gubuntu** [comment]
I reckon the custom theme repo is a good enough way to do it so closing
