### ISSUE TITLE
aggregation not working?

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#375]
on testing I did an analysis choosing two aggregation polygons. 

Only one map and report were produced with no breakdown per aggregation layer

**Comment by myarjunar** [comment]
@gavin this is expected. even InaSAFE desktop itself would give only one map report except we enable map atlas report setting. Enabling map atlas to GeoSAFE would be another thing to do. If the map report shows only selected polygon and only selected polygon appears in aggregation breakdown report, we could say that the aggregation is working.

**Comment by gubuntu** [comment]
OK I can understand the map report showing the aggregate of all the selected polygons (is that what it does?) but I would expect the report to show results for each polygon as well as the aggregate. 

In this case I chose two polygons, so how should I interpret the result?

can you comment @timlinux ?

Please create a new ticket in the Funnel for enabling and handling atlas reports.

**Comment by gubuntu** [comment]
@myarjunar thanks for creating the atlas report ticket in https://github.com/kartoza/geosafe/issues/379.

Please respond to my other questions above

**Comment by myarjunar** [comment]
> In this case I chose two polygons, so how should I interpret the result?

Other than the atlas reports, you can see the aggregation result in the table report. There is already section to describe the detail report of each aggregation areas.
