### ISSUE TITLE
no basemap in report

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#376]
I did an analysis on testing (flood on roads) and there's no basemap in the report

**Comment by myarjunar** [comment]
this is also expected if we refer to the default behavior of InaSAFE desktop, but we supposed to be able to add this. Let's hope we don't need to change anything in InaSAFE core code.

**Comment by gubuntu** [comment]
when you do https://github.com/kartoza/geosafe/issues/300 please add a basemap in the template (this was requested by INGC in #311)

**Comment by gubuntu** [comment]
a map report is rather meaninngless without a basemap

[gavin flood on minplants_map.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46ef958c2a8cc3af83e6b047e452fed4244f29632505ad3f63baee29af0037431f1d11f6140b1b56f6eb8c23f7b46878dc085fec84680a74936f11acbed618eb05bf32975dc7e7e2de139db17770a599855d3f170f198cfb5c35a7994cc950f44de75f18.pdf)

**Comment by gubuntu** [comment]
add a QSM tile url to the report project. If we can't get that to work a fallback will be to use a local WMS layer or map

**Comment by lucernae** [comment]
@gubuntu @myarjunar Basemap added now.
Now, we should decide which layer contexts we want to put into the map. Certainly putting too many contexts is quite confusing (even though it is technically possible).

**Comment by gubuntu** [comment]
nice work @lucernae

**Comment by NyakudyaA** [comment]
Basemap added to the reports
