### ISSUE TITLE
buggy analysis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#380]
from @cgiovando
>analyses in testing.geonode.kartoza.com are still very buggy, lots of missing images, buttons not responding, intermittent 502 and 503 errors, missing legend icons/values/text, confusing mix of EN/PT text...

**Comment by myarjunar** [comment]
could you give me more details on this? server crashing issue should be fixed already.

**Comment by lucernae** [comment]
Confusing mix of en and pt is because we don't yet have full PT translation yet.

**Comment by gubuntu** [comment]
also from @lucernae 
>Please try it again. As I said before, most of it because the layer have faulty metadata. I upload a clean one again today and it's working fine so far. when you upload again, check the metadata.

**Comment by NyakudyaA** [comment]
I have tested a couple of analysis on Mozambique with the new metadata and they all complete in good time.
After running the analysis on flood on powerline the report has some issues with wording
![result](https://user-images.githubusercontent.com/2510900/46901862-a3603e80-cebb-11e8-8bba-8b1408b654b4.png)

I ran flood on powerline but the report refers everything to as roads

**Comment by myarjunar** [comment]
@NyakudyaA InaSAFE still doesn't have a definition for powerline exposure. I guess somebody who created that layer use road as a type of exposure in the keyword wizard.

**Comment by NyakudyaA** [comment]
> @NyakudyaA InaSAFE still doesn't have a definition for powerline exposure. I guess somebody who created that layer use road as a type of exposure in the keyword wizard.

 I understand. So the results are all good

**Comment by gubuntu** [comment]
not good from a user perspective. I suggest removing the keywords from the powerline layer (and other layers for which there is no impact function) and just leave it there as a GeoNode layer.

**Comment by lucernae** [comment]
@gubuntu can you communicate with Cristiano about this? I think the one that he mentioned has exactly this same issue described in this ticket.

**Comment by NyakudyaA** [comment]
Fixed. Layer will not appear as exposure layer
