### ISSUE TITLE
confirm locale behaviour

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#382]
@lucernae after https://github.com/kartoza/geosafe/issues/291 can you confirm whether InaSAFE headless, GeoSAFE and GeoNode switch locales between EN and PT based on user locale and that user can override?

And that other non-available languages are removed from locale options?

**Comment by lucernae** [comment]
@gubuntu The way that it works:

1. Browser will take language settings from the computer
2. Django will take that settings and saves it on the cookie to remember it next time
3. User can switch to language, even though it is different from their computer settings. This changes will be saved (currently the button is at the bottom).
4. The whole text in site will rely in this settings to set language. The locales passed on to Headless will take from current user configurations (not implemented yet, but planned to behave like this). This allow you to create multiple report on different language on the same site.
5. Non-available languages can be removed, yes. We will plan to remove non-available language from the theme app.

**Comment by lucernae** [comment]
Locale changes should be seen in the testing sites

**Comment by gubuntu** [comment]
yes I switched between pt and en nicely. 

when should headless locale switching be implemented?

**Comment by NyakudyaA** [comment]
@gubuntu I also could change between the languages nicely. We can close this

**Comment by gubuntu** [comment]
@NyakudyaA please test that text and map reports are also in ingc theme and in pt.

**Comment by NyakudyaA** [comment]
Yes I am currently running an analysis in PT

**Comment by myarjunar** [comment]
@gavin @NyakudyaA  I'm still doing the last check and fix on custom template. I will let you know once it gets deployed.

**Comment by NyakudyaA** [comment]
Ok @myarjunar I have ran an analysis and if failed with some errors. I will create a new issue for it

**Comment by NyakudyaA** [comment]
I ran the analysis and the text and theme are still in the old GeoSAFE themes. Perhaps @myarjunar still busy fixing this as it relates to custom templates

**Comment by NyakudyaA** [comment]
@myarjunar cc @lucernae the InaSAFE variables are not being substituted in the reports properly
![screenshot 2018-11-07 at 08 56 50](https://user-images.githubusercontent.com/2510900/48115314-2e3e1a00-e26b-11e8-9629-fa4a6ffcec2a.png)

The table report - has it been translated , it is only available in English ?.

**Comment by myarjunar** [comment]
whoa, can you point me to the analysis page? @NyakudyaA

**Comment by NyakudyaA** [comment]
@myarjunar http://testing.geonode.kartoza.com/geosafe/analysis/create/80

**Comment by lucernae** [comment]
My bug sorry! It has been fixed in this commit: . :D
https://github.com/inasafe/inasafe-headless/commit/2dccbe38497fc274dc1f033579260bf8b990ed38

**Comment by NyakudyaA** [comment]
@myarjunar I assume the table will also be translated when a new InaSAFE is released. Otherwise, everything is working properly on this ticket.

**Comment by lucernae** [comment]
The next step up is to include the table template in Django, so Django wil handle the template translation and generation (it doesn't have to rely on InaSAFE strings).

**Comment by gubuntu** [comment]
@lucernae can you put that in a new ticket (in Funnel) then close this one please

**Comment by NyakudyaA** [comment]
#502
