### ISSUE TITLE
Map report should show context layers

### ISSUE THREAD

**Issue by timlinux** [kartoza/geosafe#385]
<img width="1643" alt="screenshot 2018-10-12 at 06 57 24" src="https://user-images.githubusercontent.com/178003/46849027-7f362c00-cded-11e8-9a1b-109592872008.png">

Can we have the other context layers shown in the map:

• hazard
• aggregation

Having the OSM tiles as backdrop would also be nice but I suspect that is going to give us printing hassles in QGIS so skip that at the first sign of trouble. (see #376)

This was also an INGC request when @gubuntu visited

**Comment by lucernae** [comment]
Yes we can. In Realtime, I originally put hazard on top of exposure and aggregation in the most top. We can statically customize the same thing here (for every impact layer, put exposure, then hazard, then aggregation if any).

> Having the OSM tiles as backdrop would also be nice but I suspect that is going to give us printing hassles in QGIS so skip that at the first sign of trouble. (see #376)

You mean is it going to be toggleable or just no basemap?

**Comment by lucernae** [comment]
CC @gubuntu which context layer we want to include in the report apart from basemap?

**Comment by gubuntu** [comment]
> Yes we can. In Realtime, I originally put hazard on top of exposure and aggregation in the most top. We can statically customize the same thing here (for every impact layer, put exposure, then hazard, then aggregation if any).

these
