### ISSUE TITLE
override defaullt zoom

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#394]
https://github.com/kartoza/geosafe/issues/301 is a good generic behaviour but for Mozambique please override it in the INGC theme, to zoom to Mozambique.

**Comment by boney-bun** [comment]
@gubuntu does this extent good enough for mozambique?
or, do you want me to zoom in a bit?

![screen shot 2018-10-15 at 7 48 03 pm](https://user-images.githubusercontent.com/4602383/46951941-aaea3800-d0b3-11e8-8937-395396e11436.png)

the GIF:
![ingcextent](https://user-images.githubusercontent.com/4602383/46952727-e84fc500-d0b5-11e8-96a7-88287089611c.gif)

**Comment by gubuntu** [comment]
I prefer the first one
