### ISSUE TITLE
analysis not working with some flood hazar layers completes, but impact layer does not draw

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#397]
it only draws if I click on it from the analysis list afterwards.

Also, the report button did non populate until I returned to the page later. 

This was the first time visiting the page since yesterday's upgrades so these issues might have been avoided with a page reload?

**Comment by myarjunar** [comment]
sorry, I don't understand the issue, could you give me more details like screenshot etc?

**Comment by gubuntu** [comment]
1. analysis completed successfully
1. report button remained empty, didn't show this or previous report
1. impact layer was not added to map

when I left to anaysis list then returned to create analysis page, all was OK. 

If you're happy that it's all working from your testing then close
