### ISSUE TITLE
not all GeoSAFE UI is translated

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#400]
e.g. button and popup strings are still english, even when site language is PT. 

Those strings probbably still need to get loaded into the transifex project

**Comment by gubuntu** [comment]
I've just translated the rest of the geosafe/django resource. I had completed the ingc resource last week but did not realise I had to do django too. I hope you can just use it and deploy!

**Comment by myarjunar** [comment]
Thanks @gubuntu , but unfortunately there are some strings left :grinning: I will let you know once I compiled the strings and pushed it into transifex.

**Comment by myarjunar** [comment]
@gubuntu I have pushed some new strings to transifex. If you find variable-like strings, just leave it as it is and only translate the non-variable-like strings.

**Comment by gubuntu** [comment]
all done. For strings with variables, I translated the non-variable segments and left the tags as is
