### ISSUE TITLE
analysis is saved whether you are logged in or not

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#403]
if you're not logged in, it's supposed to be ephemeral.

either change the message or change the behaviour

**Comment by myarjunar** [comment]
@gavin we already have a scheduled task for this, see https://github.com/kartoza/docker-geosafe/blob/develop/src/core/geosafe.py#L84 . I've checked in testing-instance's rancher and it seems like the task ran properly. cc @lucernae

**Comment by myarjunar** [comment]
@gubuntu we already have a scheduled task for this named `clean_impact_result` and run every 0:00 AM. I've checked in testing instance rancher and it seems like the task ran properly. cc @lucernae

**Comment by NyakudyaA** [comment]
Tested. When a user is anynomous the results are not saved.
![screenshot 2018-10-25 at 15 09 28](https://user-images.githubusercontent.com/2510900/47502443-14163c00-d868-11e8-81eb-984aedfcab59.png)
