### ISSUE TITLE
Layer markers in the wrong place

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#404]
layer markers are drawing at the lower left corner of the layer bounding box instead of at the centroid

**Comment by NyakudyaA** [comment]
@boney-bun I am going to close this and do another ticket with regards to these markers. There seems to be a new bug.

**Comment by gubuntu** [comment]
Ok @NyakudyaA but in future keep the same ticket open, takeit back to In Progress and add a Regresssion label
