### ISSUE TITLE
Draw blue border for layer indicator if there is layer

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#41]
Draw the icons in blue by default if there is some data for the type (i.e. if there is a triangle) and only draw them in gray if there is NO data for the type.

**Comment by gubuntu** [comment]
icons colours now looking good and behaving as requested. Not sure how the border comes into this?

**Comment by lucernae** [comment]
originally, icon and the border should be gray if nothing is selected, should display triangle if it contains more than one children, and should be blue if it is only one children. Lastly, it should be green (with or without triangle) if selected.

I found this too complicated for the user, so I delete the rule for blue border and icon when it is only one children. Blue now means if there is data and it is not selected, (if selected, it becomes green).
