### ISSUE TITLE
Make the hazard and exposure icons in the menu bar bigger to match the others

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#42]
@timlinux @gubuntu In my opinion all these icons were already evenly sized. Maybe because exposure and hazard has more uncolored area so it is apparently small.
I will just resize all icons to fill its maximum space instead.

Like this:
<img width="214" alt="screen shot 2017-02-14 at 20 22 51" src="https://cloud.githubusercontent.com/assets/831865/22930551/6982d632-f2f3-11e6-8a70-335049e74cc6.png">

**Comment by gubuntu** [comment]
LGTM
