### ISSUE TITLE
Layer markers are not visible at all scales

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#423]
# Problem

Whilst fixing  #404  there are bugs that were introduced
* Default view is empty - No markers are visible
* Zooming in - No markers are visible
* Zooming out - Markers are visible at only one scale level

# Solution
Make it happy

**Comment by gubuntu** [comment]
@boney-bun we should have no regresssions with adequate unit tests and user testing. We can't have things like this happening the day before the demo

**Comment by boney-bun** [comment]
there was a mistake with previous PR (https://github.com/kartoza/geosafe/pull/416) due to the use of github's suggestion feature.
i have made an urgent patch here: https://github.com/kartoza/geosafe/pull/420
so, i guess this is no longer valid.

can you test it again @NyakudyaA ?

**Comment by NyakudyaA** [comment]
I have tested this again. The default view shows all the markers and zooming out they still appear. If you zoom in the markers are replaced by rectangles. This is the expected behaviour
