### ISSUE TITLE
improve communication of "exposed" and "affected" in analysis summary

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#427]
from @cgiovando 
> improveme how "exposed" and "affected" are presented to the user - which doesn't seem very clear at the moment.

![screen shot 2018-10-29 at 16 59 19](https://user-images.githubusercontent.com/496911/47843454-52f84480-ddc8-11e8-875c-e2d52dd00cfb.jpg)

 related to #434

**Comment by NyakudyaA** [comment]
looks better in the printout below.

![screenshot 2018-11-13 at 20 08 28](https://user-images.githubusercontent.com/2510900/48433500-eb56d780-e77f-11e8-99e6-86c48776b520.png)
