### ISSUE TITLE
report does not give aggregation layer breakdown

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#428]
I chose three aggregation polygons for this analysis yet there's no mention of aggregation in the report. I expect to see details about each polygon plus the summary / aggregation of all of them put together. 

[gavin flood on minplants_table.pdf](https://github.com/kartoza/geosafe/files/2538257/gavin.flood.on.minplants_table.pdf)

**Comment by myarjunar** [comment]
@gubuntu tested using Padang villages aggregation layer and it works fine. I think the problems are with the aggregation layer keywords. cc @NyakudyaA 

![selection_303](https://user-images.githubusercontent.com/11134669/47854194-b3f93a00-de13-11e8-88cb-4fcef89fff38.png)

**Comment by NyakudyaA** [comment]
@myarjunar I will look at the keywords. I did not generate them. @raisserafael generated all keywords and I just applied them.

**Comment by NyakudyaA** [comment]
I have just confirmed this is the case with the keywords version. Any aggregation layer generated with keywords version 4.4 will not produce any results.
I deleted Sofala and uploaded it with InaSAFE keywords version 4.3 and here are the results
![screenshot 2018-11-02 at 14 23 34](https://user-images.githubusercontent.com/2510900/47915248-ec982280-deaa-11e8-8548-01811d85e19d.png)

![screenshot 2018-11-02 at 14 24 23](https://user-images.githubusercontent.com/2510900/47915283-08032d80-deab-11e8-86cb-879e5ea5552c.png)

@myarjunar cc @lucernae maybe we should tell people to use a specific version of InaSAFE to generate the keywords same like what we used to do for version 3.5

**Comment by gubuntu** [comment]
there surely shouldn't be any difference in behaviour between minor versions. 

InaSAFE and GeoSAFE should work properly with keywords from any 4.x version.

**Comment by myarjunar** [comment]
@gubuntu @NyakudyaA I can reproduce the bug on InaSAFE desktop using test data. I will work on it.

**Comment by lucernae** [comment]
Ouch, so this bug came from InaSAFE??? @myarjunar

**Comment by myarjunar** [comment]
ups sorry, it turns out that the problem is not coming from InaSAFE, it's from the keywords, see https://github.com/kartoza/geosafe/issues/433 .

**Comment by gubuntu** [comment]
> ups sorry, it turns out that the problem is not coming from InaSAFE, it's from the keywords, see #433

that's a separate issue - only the river catchments don't have an aggregation field. We've been using postos till now, where the keyword version is the issue - confirm please @NyakudyaA and have you changed the keywords to 4.4 and checked that they work?

**Comment by NyakudyaA** [comment]
@myarjunar Please check the difference in metadata generated by ver 4.3 and 4.4 and see how it affects  running analysis. All metadata for layers loaded were generated from InaSAFE desktop ver 4.4

**Comment by myarjunar** [comment]
@NyakudyaA it doesn't affect the analysis. I have tested it using InaSAFE metadata ver 4.4 and all looks fine, aggregation breakdown is reported. Are you sure you have set the metadata up properly? Or maybe you can share the data if it's not too big.

**Comment by NyakudyaA** [comment]
@myarjunar you can download the postos from the geonode. Alternatively please see the following postos.
[Archive.zip](https://github.com/kartoza/geosafe/files/2554704/Archive.zip)

**Comment by myarjunar** [comment]
@NyakudyaA @gubuntu aggregation breakdown only applies to affected exposures. so when there is no aggregation breakdown report meaning there are no affected exposures. I tried an analysis using aggregation area where the exposure intersects with wet hazard class (majority of the Flood Map polygons are dry class) and it generates the aggregation breakdown report. 

![selection_305](https://user-images.githubusercontent.com/11134669/48093167-3aad7d00-e241-11e8-849f-721fc080209f.png)

![geonode ingc gov mz - mozilla firefox_306](https://user-images.githubusercontent.com/11134669/48093176-400ac780-e241-11e8-87ce-edd184625d0d.png)

**Comment by gubuntu** [comment]
OK, so this was a red herring...

thanks for investigating, at least now we know
