### ISSUE TITLE
impact layer won't draw

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#429]
If I go to the Create Analysis page and try to toggle one of the available Impact layers (without choosing any hazard, exposure or aggregation layers), nothing happens...

I would expect it to zoom into the extent of the layer I choose and render it.

**Comment by NyakudyaA** [comment]
@gubuntu this is working for me. I have tried a couple of layers from testing and they zoom to the extent of the impact layer and actually render fine

**Comment by gubuntu** [comment]
I'm doing a demo on INGC, if it's working on testing that doesn't help...

**Comment by NyakudyaA** [comment]
Even on INGC it is working for me. I have just tested with `gavin flood on miniplants` and also `flood on health facilities`

**Comment by gubuntu** [comment]
doesn't work for me (latest Firefox on Mac) even after reloading the page

**Comment by NyakudyaA** [comment]
Ok, I will try it on chrome and firefox. I am using Safari

**Comment by myarjunar** [comment]
does this happen on pt only @gubuntu ? I'm working on it

**Comment by gubuntu** [comment]
yes I was on pt
