### ISSUE TITLE
We need more aggregation options

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#433]
At the moment we just have _postos_ by province

Add InaSAFE 4.4 keywords to all aggregation layers:
- [x] postos_ national layer (same as 'administative division ')
- [x] provinces
- [x] river catchments

@NyakudyaA can help

**Comment by NyakudyaA** [comment]
> At the moment we just have _postos_ by province
> 
> Add InaSAFE 4.4 keywords to all aggregation layers:
> 
> * [ ]  postos_ national layer (same as 'administative division ')
> * [x]  provinces
> * [x]  river catchments

This layer cannot be used to generate keywords because it lacks the necessary attribute table fields. Please, @raisserafael add the names of the basins if you have access to them and then it can be usable in GeoSAFE. For now I will leave it as a context layer
> 
> @NyakudyaA can help
