### ISSUE TITLE
Make the save analysis slidermore easy to understand what it will do

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#44]
@gubuntu @timlinux if slider makes it more complicated, how about just showing a checkbox with label on it 😄

**Comment by gubuntu** [comment]
not sure where this is, I jsut see a save analysis button

**Comment by gubuntu** [comment]
@MariaSolovyeva this issue is older than our UI session, can you perhaps expand on it and indicate if it is covered by one of your issues?

**Comment by gubuntu** [comment]
ping @MariaSolovyeva

**Comment by MariaSolovyeva** [comment]
I don't know where is the slider mentioned, there were too many button above the "Save analysis" button. That issue is covered by #73
