### ISSUE TITLE
add link to documentation / user manual

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#443]
The pdf of GeoSAFE user and technical documentation is at https://drive.google.com/open?id=0B2pxNIZQUjL1Q1RkVHhVTXAzOWc

Can we put a 'Documentation' or 'Manual' link in the GeoSAFE menu on INGC before the demo? 

or in another place, open to suggestions

**Comment by lucernae** [comment]
Yes, it's definitely best to put some links in the website itself.
Thanks for the document @gubuntu !

I suggest we put the manual on GeoSAFE repo too (as a file, raw and pdf maybe). Then link the manual to raw files on github repo. We can't create download link with google drive, but we might be able to create download link in Github. If that's not possible, then it will just be a redirect link.

Do you want to put the docs in GeoSAFE menu or custom INGC skin?

**Comment by gubuntu** [comment]
> Do you want to put the docs in GeoSAFE menu or custom INGC skin?

GeoSAFE  menu

I edit maintain an odt in Drive and save it as a pdf after updating it - the pdf is always at that link. I guess we could move the odt from Drive to GH

**Comment by gubuntu** [comment]
I've moved the odt to GH (ingc_geonode_theme)

although @lucernae I think the manual (odt and pdf) should be in kartoza/geosafe since they are generic.

**Comment by NyakudyaA** [comment]
This is working properly.
@gubuntu can we replace some of the screenshots in the PDF they are poor quality and resolution.

**Comment by gubuntu** [comment]
thanks @NyakudyaA, I think they are low-res because of the odt export settings, I'll adjust that on my next export
