### ISSUE TITLE
Make little help bubbles that pop up for hints when you first load the analysis page.

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#45]
They should help you understand what steps you need to take e.g.

**Comment by gubuntu** [comment]
'Run analysis' popup does not disappear and also obscures other popups. 

Also pls change its text to 'If hazard and exposure are selected, you can run an analysis'

**Comment by timlinux** [comment]
Maybe adding an [x] icon to dispatch the bubbles would be good....
