### ISSUE TITLE
PT EQ table report completely untranslated

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#450]

**Comment by myarjunar** [comment]
fixed in https://github.com/inasafe/inasafe/pull/5042 , but we still need to wait until headless point into `inasafe_4` branch on inasafe. or release new version of inasafe 4

**Comment by Vries14** [comment]
Strings to be translated with new release

**Comment by gubuntu** [comment]
@Vries14 please close only when the fix appears in production

**Comment by NyakudyaA** [comment]
String are now translated
