### ISSUE TITLE
issues with new user permissions and loading analysis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#452]
Please clarify the permissions of new users and what roles they need to be given to have minimal public functionality. 

An example is 'bontje' from the WB whom I created as a user last week but did not change any permissions. 

She can log in and see some GeoNode layers but the GeoSAFE analysis page and layers did not load properly

IS this indeed a user permission issue, a browser issue or a bug?

![image001.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46e1999b2487d3f9deabf301b44fff9e2c4533317346f67371d7e770b9467f500a5a1bac140a5f44faad8e7fa2b32e6c981e5ab38532022d8c6853beb2901eb80bbb258f4e83b1b58c44c6ef3b27f5c6.png)

**Comment by NyakudyaA** [comment]
@gubuntu this might be browser issues and connectivity issues. 
Currently with no permissions allocated anonymous users can see the public layers and run analysis.
So if a registered user logs in without having any permissions changed he should be able to see those anonymous layers and run an analysis.
![bug](https://user-images.githubusercontent.com/2510900/48199246-3cbc2c80-e364-11e8-99fb-2e94453db97e.png)

**Comment by gubuntu** [comment]
Bontje was using  IE 11. 

@boney-bun @myarjunar years  ago the intent was to make this cross-browser compatible and support the official WB version of IE and do testing with selenium or similar to support this. 

What sort of effort are we looking at to make this work on IE 11?

**Comment by gubuntu** [comment]
IE 11 compatibility no longer required
