### ISSUE TITLE
Broken Analysis list in production

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#463]
# Problem

In production,
![screenshot 2018-11-13 at 11 43 03](https://user-images.githubusercontent.com/2510900/48404700-84aecb00-e739-11e8-8e4f-ff9886375755.png)
 the analysis list is broken

Solution
Please fix

**Comment by gubuntu** [comment]
@boney-bun if you can't fix this now please assign to @lucernae

**Comment by boney-bun** [comment]
is this related to #467?

**Comment by NyakudyaA** [comment]
@boney-bun they are two separate issues. This ticket just talks about the ability to see the analysis list.

**Comment by boney-bun** [comment]
looking at the log:
```
File "/usr/src/geosafe/models.py", line 270, in get_default_impact_title
11/14/2018 1:59:22 PM    self.hazard_layer.name,
11/14/2018 1:59:22 PMAttributeError: 'NoneType' object has no attribute 'name'
```

the error is due to hazard_layer is None
 it seems that the error is related to #467

if @myarjunar fix #467 then the analysis list page can load properly.

**Comment by NyakudyaA** [comment]
> looking at the log:
> 
> ```
> File "/usr/src/geosafe/models.py", line 270, in get_default_impact_title
> 11/14/2018 1:59:22 PM    self.hazard_layer.name,
> 11/14/2018 1:59:22 PMAttributeError: 'NoneType' object has no attribute 'name'
> ```
> 
> the error is due to hazard_layer is None
> it seems that the error is related to #467
> 
> if @myarjunar fix #467 then the analysis list page can load properly.

@boney-bun for now can we just delete that impact analysis result so that we can get the analysis loading whilst we wait for the fix

**Comment by lucernae** [comment]
Yes, definitely related with #467 .
Just delete Analysis object that do not have hazard/exposure thru Admin page, if this problem persists.

**Comment by lucernae** [comment]
I deleted these botched Analyses for now.

**Comment by NyakudyaA** [comment]
This has been sorted for now by manually deleting the analysis. Will close this and monitor the related PR to fix the issue that caused this
