### ISSUE TITLE
these strings not in Transifex

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#471]
1. Planejamento de Contingência facilitado. on landing page. This translation is wrong but it is not on Transifex???? it should be 'Planeamento de contigência rápido'
1. De O Quê Se Trata? should be De o quê se trata? It is correct in Transifex but not in GeoNode

**Comment by myarjunar** [comment]
@gubuntu 
1. whoa I can't find it either. will look at it more deeply
2. It is because we are using `capitalize` tag from the HTML. It also affects the English one. Do you want me to remove the tag and just apply the strings as it is?

**Comment by boney-bun** [comment]
@gubuntu it's my bad.

i change the word according to your feedback manually in the last minute (it was about to demo). the word `Planejamento de Contingência facilitado` was taken from google translate. the original version was InaSAFE made easy.

**Comment by myarjunar** [comment]
@gubuntu @boney-bun ah we only need to pull new translations from transifex.

**Comment by gubuntu** [comment]
correct versions are above - but they shoud be in Transifex not hard coded (@boney-bun if you make a quick hack fix you must remember to un-hack it afterwards and do it properly!)

And rather remove the capitalisation tag and leave original capitalisation, it's different in each language

**Comment by boney-bun** [comment]
@gubuntu yes, apologize for not un-hacking it.

the latest translation is in transifex now.
one more question: the current PT for `What Can It Do?` is `De o quê se trata?`. 
is this correct?

**Comment by Vries14** [comment]
Correct translations added to landing page
