### ISSUE TITLE
add labels to aggregation layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#486]
It will help the user decide which posto or watershed or province to choose

**Comment by NyakudyaA** [comment]
Added labels for national postos and watershed. Restricted the labels to only appear draw if they completely fit a polygon. This will result in less clutter and since the user will zoom to choose an analysis this is better

**Comment by gubuntu** [comment]
+1

what about provinces?

**Comment by NyakudyaA** [comment]
> +1
> 
> what about provinces?

Will add them

**Comment by NyakudyaA** [comment]
Added labels for Provinces and districts
