### ISSUE TITLE
can't use landcover

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#488]
well, you can, but the legend is very unwieldy

![Screenshot 2018-11-15 at 15.57.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7851e32a64c5b27df1172c4f5c5d5cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfd5d3fa19c4fca5aff4be24c5ca51a3771ab.png)

**Comment by NyakudyaA** [comment]
Yeah, the legend class that @raisserafael used is very wide. Maybe it needs a horizontal scrollbar and to fit in the legend div

**Comment by gubuntu** [comment]
it does have a horizontal scrollbar and because it has a scrollbar it should have a fixed width, which it doesnt.
