### ISSUE TITLE
unintelligible impact layer legend

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#498]
# problem

as a casual user, I wouldn't have a clue how to interpret the legend of this layer `mz_h25 on hrsl_moz_pop_deflate`

![Screenshot 2018-11-21 at 08.56.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7b55e32a64c5b370f1172d4f5b5e5cb053181d1ba6acda6fb4bc2e75820d09b9d93b0b20c76814f9b8d74dbf01bc748c1b81b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fca5ffe48e74c50a6143571ab.png)

# solution

- fix the InaSAFE keywords? (why are there generic classes rather than flood classes?)
- do somehting else?

**Comment by NyakudyaA** [comment]
This has already been fixed. All flood layers are defined as generic because in the classification of the metadata the flood is in cm and there is no units to assign them in InaSAFE
