### ISSUE TITLE
Add a registration option

### ISSUE THREAD

**Issue by Vries14** [kartoza/geosafe#501]
Bug report

There are no options for unregistered users to get registered. To only path to get yourself registered is by entering the wrong details in the sign in page

**Comment by NyakudyaA** [comment]
This is untrue. They are multiple options listed on at the bottom of the page.
![screenshot 2018-11-23 at 18 24 03](https://user-images.githubusercontent.com/2510900/48952999-ff9f8f00-ef4c-11e8-95c2-fdac16ea65d0.png)
