### ISSUE TITLE
Integrate ansible to development environment setup

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#52]
So it can be easier to set up the IP, etc

**Comment by Gustry** [comment]
What about the previous one we did ?

**Comment by gubuntu** [comment]
please merge the one you did into our Gitlab devops repo and take it from there

**Comment by lucernae** [comment]
> please merge the one you did into our Gitlab devops repo and take it from there

It's a different one, this one is to setup development environment, like pycharm configuration and celery configuration.
Gitlab will be used for deploying it into production.

> What about the previous one we did ?

I think it will be very different. For deployment, we now want to use ansible + rancher if possible.

**Comment by gubuntu** [comment]
@lucernae can we not close this?

**Comment by lucernae** [comment]
Yes, I think we can close this.
