### ISSUE TITLE
osm roads and buildings layers are not restricted to Mozambique

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#530]
fix docker-osm, it's pulling roads and buildings for a much larger area than Mozambique (and also not generating thumbnails)

**Comment by NyakudyaA** [comment]
@gubuntu I will look it up and fix. With the thumbnail, there is nothing I can do because the data is too big and qgis server times out whilst generating a get map request.

**Comment by NyakudyaA** [comment]
Osm roads now fixed, Still trying to figure out why the osm-buildings are not working properly. Even if the data is for the whole province the extent specified in the qlr should filter this properly

**Comment by NyakudyaA** [comment]
All fixed now
![screen](https://user-images.githubusercontent.com/2510900/54821447-da2c5300-4caa-11e9-9c46-cd843e0eff37.png)
![osm](https://user-images.githubusercontent.com/2510900/54821449-dac4e980-4caa-11e9-8679-42b87decab63.png)
