### ISSUE TITLE
Use direct  disk access when doing analysis

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#54]
All the layers handed over from InaSAFE headless to GeoSAFE or vice versa might be better directly accessed from the disk (via docker volume mount), rather than via http request

- there is already an option to use file uri rather than url. At the moment geosafe is using url - change to file uri
- share data filesystems into processing nodes

**Comment by gubuntu** [comment]
this is part of the solution to #78

**Comment by gubuntu** [comment]
@lucernae this is complete, right? Please close
