### ISSUE TITLE
Migrate celery to v4

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#55]
Also provides unit test for migrations

**Comment by gubuntu** [comment]
@lucernae is this going to happen in August? Is it essential? Part of InaSAFE 4 upgrade? Please clarify and move to backlog if low priority

**Comment by gubuntu** [comment]
ping @lucernae 

and is this part of what @akbargumbira is doing? If so please label In Progress

**Comment by gubuntu** [comment]
GeoNode has now upgraded to Celery 4 so when we merge this should close
