### ISSUE TITLE
Implement Continous Testing and Delivery

### ISSUE THREAD

**Issue by lucernae** [kartoza/geosafe#57]
Implement systematic TDD for Pull Request (or might be possible with Travis - docker)
   - Learn git webhook
   - Need a test server
   - Need to spin up celery based testing, (including broker and worker), might need ansible
   - Container order and spin up rule
   - Testing scripts.

**Comment by Gustry** [comment]
Can't we use the geonode architecture ?
Because we need to do that for the QGIS Server backend ? As it will be integrated in the geonode repo,  we will need to setup and write tests for their architecure.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/docker-geosafe#49
