### ISSUE TITLE
Write GeoSafe install documentation

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#60]
We need some basic documentation for anyone to be able to
- install GeoSAFE into existing GeoNode instances.
 - Camp2Camp needs to swap Labs Geonode (http://45.55.174.20/) to QGIS-Server and install GeoSAFE
- install Geonode with GeoSAFE, from scratch
- upgrade a Geonode-GeoSAFE instance
- set up a development environment (Kartoza's Ansible approach)

**Comment by gubuntu** [comment]
The deployment project https://github.com/kartoza/docker-geosafe will have documentation but that will deploy everything. 

I think that project should be extended to also be able to upgrade or convert and existing Geonode instance (and then documented there). @timlinux @lucernae what do you think?

**Comment by lucernae** [comment]
I think, for now we can have documentation on docker-geosafe to cover these use cases.

**Comment by gubuntu** [comment]
@lucernae is all the documentation in docker-geosafe README? If so, can we update references from lucernae fork to kartoza fork?

**Comment by lucernae** [comment]
I had several question:

* Does Camp2Camp uses Geonode master? 
* If so, can we point them to use our geonode fork? If they need to use specific version of Geonode, we might need to explicitly support them, since older version of geonode only works with old qgis-server backend (the one we have in geonode_qgis_server repo).

**Comment by gubuntu** [comment]
This is related to https://github.com/kartoza/geonode/issues/160

@fvanderbiest @fjacon @stufraser1 can you answer @lucernae's questions above?

**Comment by gubuntu** [comment]
@fvanderbiest @fjacon @stufraser1 consider this branch to be 'stable' for Labs GeoNode. https://github.com/kartoza/geonode/tree/2.6.x-qgis_server. Stable in the Geonode sense, i.e. staying with 2.6. QGIS backend and Geosafe development and integration will be merged frequently from master-qgis_server, which is our main development branch.

note @lucernae

**Comment by fvanderbiest** [comment]
Hi guys, sorry for the lag.

> Does Camp2Camp uses Geonode master?

No, we're currently hosting integration labs geonode 2.5.4 on docker at http://int.geonode-gfdrrlab.org/
Current (and soon former) production (http://45.55.174.20/) is a geonode 2.4 with several hazard-related patches.

Since GeoSafe requires GeoNode 2.6, we're working on the upgrade to 2.6.

**Comment by gubuntu** [comment]
WIP at https://github.com/kartoza/geonode/wiki/QGIS-Server-Backend-Configuration and the README at https://github.com/kartoza/docker-geosafe

**Comment by gubuntu** [comment]
Latest docs for simplified Ansible-based non-development deployment with easy GeoSAFE on/off options are at  https://github.com/kartoza/docker-geosafe/blob/develop/deployment/ansible/README.md.

**Comment by gubuntu** [comment]
Latest with Rancher implementation are at https://github.com/kartoza/docker-geosafe/blob/develop/deployment/production/docs/Rancher.md

**Comment by gubuntu** [comment]
@fvanderbiest have you tried out our Rancher orchestration? If so, do you have any feedback?

**Comment by fvanderbiest** [comment]
Hi @gubuntu Thanks for the update !
I've had a quick look and this looks very good, but I've not had time to deploy it for now.
Maybe the GFDRR team is interested in giving it a try ?
