### ISSUE TITLE
Landing page needs improvement

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#62]
The purpose of the landing page is to introduce the user to the project and then allow the user to:

- Learn what project is about
- Lean what he can do
- Perform analysis
- Learn about other functions

## Landing page elements:

- [ ] Project intro, which explains GeoSafe as multi-hazard resource, where and how it is installed
- [ ] What we can do - functions review 
- [ ] Functionality explanation - how analysis should be done by a simple user - 3 steps
- [ ] Duplicate the main menu buttons to the body as CTA with brief description
- [ ] The ThinkHazard-like search input? - to be discussed
![think-hazard](https://cloud.githubusercontent.com/assets/10400420/24192259/62808668-0eff-11e7-8dc1-7cba193ff584.png)

## The existing page elements updates:

- [ ] Rename Create Analysis link to Perform Analysis - in the menu bar
- [ ] Make the menu buttons more informative and descriptive in order for simple user to understand their functionality.

**Comment by gubuntu** [comment]
you can user moqups.com if you like, log in through Google with your Kartoza account

**Comment by boney-bun** [comment]
@gubuntu @MariaSolovyeva please review the landing page [here]( https://app.moqups.com/boney@kartoza.com/mvSQpBxcMV/edit/page/aa6b976cf)
if we have javascript, all the explanation can be seen in a single window by scrolling down

btw, I need more explanation about CTA and ThinkHazard.

**Comment by boney-bun** [comment]
screen shot of the proposed landing page is copied below.

![screen shot 2017-05-08 at 8 18 52 pm](https://cloud.githubusercontent.com/assets/4602383/25796003/f7ffc144-342b-11e7-944f-c27a696bcb1c.png)

**Comment by gubuntu** [comment]
@boney-bun not Tim's comment in Gitter and also, choose Hazard before Exposure in 3rd screen. 

2nd screen: put Metasearch last

1st screen - did you make that up or copy from somewhere? Nice but second sentence a bit awkward and inaccurate, try to craft something better. 

Otherwise nice concept, go ahead and implement

**Comment by gubuntu** [comment]
@boney-bun and @dimasciput this was received favourably, thank you

Two final enhancements:
- [ ] add a representative graphic such as a screenshot of an analysis to illustrate each section 
- [ ] change the navigation icons to be softer hover areas with a down arrow. Not hard 'click me out of here' buttons.

**Comment by boney-bun** [comment]
@gubuntu below is the illustration of the enhanced version for the landing page
![enhanceui62](https://cloud.githubusercontent.com/assets/4602383/26565644/0ae125ac-4541-11e7-9d12-337b5614fc34.gif)

**Comment by gubuntu** [comment]
Looking nice - please make all the fonts and text layout consistent and also move the illustrations to the left of each block of text. 

Also take note of the other checkbox items higher up in this Issue.

**Comment by dimasciput** [comment]
Please add padding from the image and the text, also the image too small and not clear.

**Comment by dimasciput** [comment]
You could maybe put the image on the left or right, and put the text on the different side. Another option is to put the slide as a background like in kartoza.com site.

**Comment by boney-bun** [comment]
@gubuntu @dimasciput here is the new layout:
![enhanceui62](https://cloud.githubusercontent.com/assets/4602383/26635022/8477ea96-466c-11e7-816a-c6fbb3f0c340.gif)
images resolution were 320x240 in the previous version.
It is 640x320 now.

**Comment by gubuntu** [comment]
Better. It might be your screenshot gif but the embedded gifs seem to be distorted? They need to stay in the same aspect ratio in which they were made.

**Comment by boney-bun** [comment]
it because the gif uses low resolution. I can't use higher resolution as the file exceeds 10 MB and GH doesn't allow it.

**Comment by gubuntu** [comment]
I'm not concerned about resolution, the aspect ratio appears distorted.

**Comment by boney-bun** [comment]
@dimasciput  @MariaSolovyeva can you  help me fixing the images so they don't appears distorted?

**Comment by gubuntu** [comment]
@boney-bun just ensure that the image aspect ratio and placeholder / css aspect ratio are the same

**Comment by boney-bun** [comment]
let me know what do you think of the latest images and texts @timlinux @gubuntu 
![enhancelandingpage62](https://user-images.githubusercontent.com/4602383/27441910-0c20417c-5799-11e7-8876-3319e61137f1.gif)

**Comment by gubuntu** [comment]
@boney-bun please add this before deploying tomorrow:

The landing page needs an obvious and inviting shortcut to the Analysis page.  Something like a button below the first text box that you can see without scrolling down that says 'Try it out...'

**Comment by gubuntu** [comment]
much better

under Metasearch: 'that publish' instead of 'publishing'

**Comment by boney-bun** [comment]
the text has been revised.
I use flask icon to represent *try it out* button. 
the *try it out* button is located next to the *arrow down* button. 
![enhancelandingpage62](https://user-images.githubusercontent.com/4602383/27467191-78ff3778-580a-11e7-9931-7f940338bb7d.gif)

**Comment by gubuntu** [comment]
nice work. Please merge for today's deployment
