### ISSUE TITLE
We need to create a warning for not logged in user

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#65]
If the user is not logged in, he cannot save the analysis. He should see the notification about it before the starts selecting the exposure and hazard layers.

**Comment by boney-bun** [comment]
A notification has added at info box. 
The notification will keep showing on the info box.
Hopefully it does not annoying for some people.

![geosafe65](https://cloud.githubusercontent.com/assets/4602383/24835275/91a69940-1d51-11e7-9085-a0e910ef1048.gif)
