### ISSUE TITLE
"Run" tooltip hover issue

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#66]
When there is only one Analysis function available - it is getting hovered by "Run" tooltip.
![hover](https://cloud.githubusercontent.com/assets/10400420/24193440/4a2a8114-0f03-11e7-8bb3-1ac8f28557f2.png)

**Proposed solution:**
- Make the tooltip visible only for a few seconds, after an action which is logically points to using the Run button
- Change the z-index when clicking on the corresponding tooltip to make it visible

**Comment by boney-bun** [comment]
This issue is not valid anymore in Geonode 2.6a as the "Run Analysis" window doesn't overlap the "Select Impact Function" window.


![geosafe66](https://cloud.githubusercontent.com/assets/4602383/24834836/34b786a2-1d44-11e7-9ff4-176785d9c274.gif)
