### ISSUE TITLE
We need to update "report" and "show summary" icons

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#68]
The report and show summary icons are not clear for the user.
We need to update them.
![report_icon](https://cloud.githubusercontent.com/assets/10400420/24193946/1caa858e-0f05-11e7-8fba-80b14381ea7e.png)
![sho_summary](https://cloud.githubusercontent.com/assets/10400420/24193949/1f164164-0f05-11e7-8a67-2d9d4a33c6b4.png)

**Comment by gubuntu** [comment]
@MariaSolovyeva could you provide clearer, more intuitive icons?

**Comment by mashastudio** [comment]
Hello @gubuntu I've picked 2 icons for each of them so you could choose

Download report:
![download-report-icon](https://cloud.githubusercontent.com/assets/10043861/25742287/74a7b09a-3197-11e7-9e21-a3f1747f0870.png)
![download-report-icon2](https://cloud.githubusercontent.com/assets/10043861/25742286/74a4317c-3197-11e7-92a5-2f401b90be35.png)

Show summary:
![show-summary-icon](https://cloud.githubusercontent.com/assets/10043861/25742303/7fbabfe0-3197-11e7-9548-dcf5b0a89bf4.png)
![show-summary-icon2](https://cloud.githubusercontent.com/assets/10043861/25742304/7fc81be0-3197-11e7-8d7e-624fd0714776.png)

Let me know, and I'll send the SVGs

**Comment by gubuntu** [comment]
@MariaSolovyeva the second one of each. @timlinux @cgiovando what do you think?

**Comment by gubuntu** [comment]
@MariaSolovyeva just go ahead with the second show summary one, we'll keep the download one.

**Comment by gubuntu** [comment]
use svg file in e267d58d1e28

**Comment by boney-bun** [comment]
Something like this?
the download icon has changed in geonode 2.7.

![screen shot 2017-05-12 at 2 22 34 pm](https://cloud.githubusercontent.com/assets/4602383/25979800/a6d6fbe8-371e-11e7-9670-762f74a0bcaf.png)

**Comment by gubuntu** [comment]
yes, though I think they should stay the original green colour?

**Comment by boney-bun** [comment]
I think the icon would change its colour depends on the user's action.
It can have the colours of: grey, white, and green.

below is the illustration of the changing colurs.
![changeicon68](https://cloud.githubusercontent.com/assets/4602383/26338468/5151cd38-3fd4-11e7-8a6d-b6e9c2fb3cec.gif)

**Comment by gubuntu** [comment]
OK go ahead then
