### ISSUE TITLE
We need to improve "Waiting for analysis to run" message

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#69]
When user is waiting for the analysis to run, he needs to see the progress bar, and how long the process is going to take. For the case he is not ready to wait as long, there should be the options available: “Cancel/Stop or Save for later”

**Comment by gubuntu** [comment]
The 'Analysis List' shows progress. A user can come back any time and see progress (?). 

So I think the easiest and most intuitive solution is to indicate to the user via a popup or similar that they should keep an eye on the analysis list page to monitor progress. Perhaps add text to the current dialog that pops up after clicking Run that says: "You can close this if you want to continue working. See the Analysis List link to monitor the progress of this analysis and so view the results when it is complete"

If there's a simple way of estimating job size or other aspects of response like server load, then also give a more meaningful message, like 'this analysis covers a large extent so might take a while' or 'this analysis uses high resolution data so might take a while'

**Comment by boney-bun** [comment]
this is the illustration of the new message and how the user can check the progress on the *Analysis List* page @gubuntu 

![improvewaitingmessage69](https://user-images.githubusercontent.com/4602383/27395665-c7af988a-56da-11e7-979e-fc5177c9a8cc.gif)

for estimating job size, it would be quite challenging as it would be influenced by many factors. 
maybe we should postpone the job estimation feature until we have all the datasets and obtaining the average time needed to process all of them on a server. then, we could statistically find a good way to estimate the job size. probably by using a simple math, such as the size of a file multiplies by the average time for processing the file, could work.

**Comment by gubuntu** [comment]
LGTM except fix the text in the message. 

analysis list link __on the home page__

and change 'so view' to 'to view'
