### ISSUE TITLE
Make geosafe usable whilst analysis is being run

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geosafe#7]
# Problem

![greyout](https://cloud.githubusercontent.com/assets/2510900/21041099/93db9856-bdf1-11e6-92bc-ebd048b6b016.png)

When running an analysis geosafe becomes unusable in that session. Opening another instance of geosafe in a  different tab a user can proceed to run analysis

* Hazard Layer - geonode:nsunga_tanzania
* Impact Layer - geonode:osm_buildings_current_tanzania

# Solution

Fix and let the analysis run in the background or send the notification to the bottom of the page and let a user continue running other analysis

**Comment by gubuntu** [comment]
i.e. asynchronous or non-modal

websockets?

or shouldn't celery be making this a non-issue

**Comment by lucernae** [comment]
Well, technically it's usable. Maybe we can just put buttons to redirect to create analysis page again if the user wants to create analysis.

The modal popup is there just to confirm that the analysis is being run and the request is accepted.

**Comment by gubuntu** [comment]
yes ever since that that popup has been there it's been non-modal (with a message that you can close it and continue working)

this is actually quite out of date
