### ISSUE TITLE
We need to create "Do another search" button

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#70]
Once the search has started, user needs to see “Do another search(/analysis)” button - which will zoom back to the world and make everything back to the global extent.

**Comment by boney-bun** [comment]
we could simply hit refresh button from the browser.
however, to make it clear to the users, I would add a refresh button on the left pane of the create analysis page.

**Comment by gubuntu** [comment]
makes sense to me

I would call it rather 'Start again'

**Comment by boney-bun** [comment]
The 'start again' button has been added to the bottom of the left pane.
![add-start-again70](https://user-images.githubusercontent.com/4602383/27038082-2b90514c-4fb4-11e7-8523-ba219bb42356.gif)

**Comment by gubuntu** [comment]
LGTM. Does it simply do a page refresh or what exactly?

**Comment by boney-bun** [comment]
when a user clicks the link, it sends the url: `/analysis/create` to the django framework.

**Comment by gubuntu** [comment]
ok, go ahead and merge
