### ISSUE TITLE
Report summary table

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#72]
User needs to see more of the results in this table. 
We need to add the small image from "Show map report" to the table.

**Comment by boney-bun** [comment]
could you elaborate more about *add the small image* @MariaSolovyeva ?
i think you might want to add the layers name on the report.

**Comment by MariaSolovyeva** [comment]
Hello @boney-bun , it is about the the map report image preview on the table, see here: 

![report-table-image](https://user-images.githubusercontent.com/10400420/27578614-49eb6602-5b2d-11e7-820c-79606ed45c3c.png)

**Comment by boney-bun** [comment]
Hello @MariaSolovyeva @gubuntu what do you think of the layout?
the buttons could be on the vertical position as @MariaSolovyeva suggested. 
however, my concern is when a user see them on a small screen.
the layout below is constructed with floating buttons so  that it (hopefully) can suit the small screen.
![screen shot 2017-07-17 at 11 26 31 pm](https://user-images.githubusercontent.com/4602383/28278527-a0152de0-6b47-11e7-9f61-7aac422680eb.png)

**Comment by gubuntu** [comment]
Yes this looks OK (Is this the thumbnail image drawing?)

But reduce the margins in the bottom cell
