### ISSUE TITLE
2 close buttons

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#74]
The download pop-up has two close buttons. We can keep the top one.

![2close](https://cloud.githubusercontent.com/assets/10400420/24199000/275416d0-0f19-11e7-8e95-46e443ff89cc.png)

**Comment by cchristelis** [comment]
This seems to be coming from GeoNode. We will have to update it upstream. @gubuntu

**Comment by lucernae** [comment]
I think this is a default behaviour for bootstrap dialog. If you ask my opinion, I think it's fine to have 2 buttons. Some people might not understand that X means close.
