### ISSUE TITLE
Text elements

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#75]
- [x] **Impact function description** (“Raster tsunami”)  - needs explanation for a simple user - what is raster - roads under water or not?
![impact_name](https://cloud.githubusercontent.com/assets/10400420/24199214/c15b327c-0f19-11e7-8eaf-9542ee270113.png)

- [x] **In the result table** hazard areas labels need explanation for a simple user (“wet”, superscript).
![labels](https://cloud.githubusercontent.com/assets/10400420/24199264/f1056b50-0f19-11e7-8a19-b2b7a4de075d.png)

- [ ] **Analysis result intro** - In the event of.. = “In the event **anywhere across the country of** Indonesia.”
It also has to be clear that Tsunami comes from hazard and roads from exposure - i.e. “In the area you’ve selected the hazard tsunami could affect exposure layer road”.
![result-intro](https://cloud.githubusercontent.com/assets/10400420/24199448/9df19f6e-0f1a-11e7-84d2-d4a0a70a6699.png)

- [ ] The units are “m”, and in the title it says “How many roads..”, better say “What length..”, then eplain to the user what does “m” mean, meters or miles?
![units](https://cloud.githubusercontent.com/assets/10400420/24199497/cdcbb2c4-0f1a-11e7-8eec-1213a2071cd5.png)

- [ ] We need to explain to the user what is defined by high or very high (level of probability or water height?)
![high](https://cloud.githubusercontent.com/assets/10400420/24199523/f0ea15d4-0f1a-11e7-9f9d-8e1175b9af87.png)

**Comment by lucernae** [comment]
>  Impact function description (“Raster tsunami”) - needs explanation for a simple user - what is raster - roads under water or not?

We can't change this at the moment, because it's coming from InaSAFE definitions. However, for InaSAFE v4, this row will disappear, because we don't have to choose Impact Function.

The rest of the comments will highly likely irrelevant in InaSAFE v4, since there is a drastic changes in InaSAFE reporting API. We should take the idea and find a way to implement it in new Reporting API.
