### ISSUE TITLE
GeoNode layer detail page

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#76]
[this is actually a GeoNode issue]

# Legend

(fix these with #192?)

- [ ] The title of legend needs to be defined 
![legend](https://cloud.githubusercontent.com/assets/10400420/24199641/7c594388-0f1b-11e7-8c12-0547154031a5.png)

- [x] We need to define the cell to the user (people per cell)(see the image above)

- [ ] The “Legend” description is out of column layout

**Comment by lucernae** [comment]
> The title of legend needs to be defined
> We need to define the cell to the user (people per cell)(see the image above)

These two were handled by user in QML files, when they define the styles in QGIS

> We need to create the button "Come back to the results" so the user could easily return to the analysis page

I think this is not possible. This is a native page of Geonode, the user can come from anywhere to this page, so it's not always from analysis page. So, supposedly we can rely on back button for this. But this is a nice input, we should make sure that analysis page can be back navigated.

> The “Legend” description is out of column layout

Yes, I think we had some problem in the CSS.

**Comment by gubuntu** [comment]
@dimasciput pls do what you can here then hand over

**Comment by gubuntu** [comment]
returning to backlog as this is not a core GeoSAFE issue

**Comment by gubuntu** [comment]
@NyakudyaA please confirm that things you can fix witht he legend are done, then reassign to Boney

**Comment by NyakudyaA** [comment]
This is more of a styling issue to put in the units. The title `Legend` is not inherited from the qml. I have looked at all the layers in Mozambique and they have legends with units except for cyclones which I will write to Jose to redo

**Comment by gubuntu** [comment]
OK...but there are still the other legend items in the OP to resolve.

**Comment by NyakudyaA** [comment]
@myarjunar I think the issue mentioned here relates to the way the analysis result is presented. I have a feeling it might have changed in InaSAFE and previously this style was hardcoded in the code to generate impact results and dynamically style them. 

Could you please comment on the above issue and close if the issue no longer exists because if it's an issue with user styling we need to encourage them to style their layers meaningfully either by putting a tip in the style tab.

If it's an impact styling how can we standardise it.

**Comment by gubuntu** [comment]
@NyakudyaA you didn't finish your sentence

**Comment by NyakudyaA** [comment]
> @NyakudyaA you didn't finish your sentence

I have finished it

**Comment by myarjunar** [comment]
@NyakudyaA The style of the impact layer is already been standardized in InaSAFE. we can close this
![selection_296](https://user-images.githubusercontent.com/11134669/47126550-5ca38780-d2b3-11e8-8882-8ad6bebe3122.png)

**Comment by gubuntu** [comment]
OK, assuming that's the same legend that come through in the GeoNode layers page and that it's consistently better formatted
