### ISSUE TITLE
Server response

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#78]
The response of the server is a little bit slow (it took about 2 seconds). Considering a slow internet connection in Indonesia and the type of machines they may use, the users may perceive a slow response of the site.

We need to make sure GeoSAFE is performing fast and well with the launch datasets

**Comment by gubuntu** [comment]
In the interim, adjust the text of the Analysis message to the following:
```
<p>
However, you can close this message if you want to continue working. <br />
Your analysis covers an area of [area] km<sup>2</sup>. The larger the area, the longer the analysis will take.<br />
See the Analysis List link on the home page to monitor the progress of this analysis and to view the results when it is complete.
</p>
```

You should be able to calculate the [area] from the bounding box with a spherical geometry library. It must be the extent that is sent to InaSAFE in #113

**Comment by boney-bun** [comment]
does this ticket relate to #69 @gubuntu ?
cmiiw, i need to add the  area size of a layer in the waiting analysis window.

**Comment by gubuntu** [comment]
yes it does relate to #69 

read the instruction carefully

**Comment by gubuntu** [comment]
@boney this needs fixing, have a look at it on staging.

**Comment by boney-bun** [comment]
fixed.
![calculatearea78](https://user-images.githubusercontent.com/4602383/27857389-b21b5d80-619b-11e7-92f4-939a6dd83112.gif)
for comparison, this is the area when the whole extent is included for the same layers:
![screen shot 2017-07-05 at 3 55 44 pm](https://user-images.githubusercontent.com/4602383/27857443-e2dd929e-619b-11e7-9908-e8716e2749c0.png)

the only concern now is  in validating the numbers.
the calculation fully relies on `Leaflet.Geodesic` library.

**Comment by gubuntu** [comment]
the numbers are still a few orders of magnitude out
