### ISSUE TITLE
Session time insecurity

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#79]
It seems that the site does not restrict the user’s session time. If a user does not sign out, the browser will always remember the user’s credentials.

**Comment by boney-bun** [comment]
yes, this issue is still valid.
apparently, the session time is managed in the geonode.
so, we should move this issue to geonode instead of geosafe.
what do you think @gubuntu @lucernae ?

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#268
