### ISSUE TITLE
User resources tabs

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#82]
On the user’s  profile  there are a list of resources. If we click a resources tab which has no content, the tabs are erased along with the content.

![user_resources](https://cloud.githubusercontent.com/assets/10400420/24294713/b8e62e90-10a8-11e7-86a1-82aa0b6c9381.png)

**Comment by boney-bun** [comment]
This problem occured in geonode 2.4 and has already resolved  in geonode 2.6 (and perhaps the later version as well). unless we are going to use geonode 2.4, so I close this issue for now @MariaSolovyeva 
![issuegeosafe82](https://cloud.githubusercontent.com/assets/4602383/25701791/f9c24a90-3121-11e7-8114-cb41c6e1b5db.gif)
