### ISSUE TITLE
User resources

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#83]
Is there a way to remove the uploaded files or saved maps? The users may create them accidentally.

**Comment by gubuntu** [comment]
direct user to standard geonode layer or map management tools where they can be deleted.

**Comment by boney-bun** [comment]
giving access to *layer management* page can be done in two ways:
- add a *layer management* link from the menu 
- add a link in *explore layers* page (the first image below) 
## image1
![Screen Shot 2017-06-21 at 12.22.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f26b7191a379ed0c2953415e4dbc21254d58eeb9cb74fce36f34985619e8d93c5d20ce6b45f8b9d71aea01ef728b4f83e2bbde48c5fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f242e94d57a616336be475306e0a.png)

which one do you prefer @gubuntu ? 
or, we do not need to develop one as the layer management has  already on the system. we just need to pinpoint the users  to locate this management tool through a training session?
 
then, the users will be directed to the *layer management* page (the second image)
## image2
![Screen Shot 2017-06-21 at 12.23.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cac11cd032f92000868ac7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f26b7191a379ed0c2952415d4fbc21254d58eeb9cb74fce36f34985619e8d93c5d20ce6b45f8b9d71aea01ef728b4f83e2bbde48c5fa2137a5dad11b61435c52dcbd4f3fb29a49c259f242e94d57a6153564e575326e0a.png)

also, we might consider to move this ticket into geonode repo as this is part of geonode functionality.

**Comment by gubuntu** [comment]
I think this is just a training issue. Standard GeoNode functionality Layer->Edit->Remove should be sufficient (please confirm that this actually does remove a layer by uploading a small layer on staging or running a small analysis and then removing the layer. 

The option to remove through Djang Admin is not an option. Only staff/admin users get access to that.

**Comment by NyakudyaA** [comment]
@gubuntu  currently remove layer does not work. Also linked to this is https://github.com/kartoza/geonode/issues/223 where layers added with remote services are not being removed.

**Comment by gubuntu** [comment]
OK closing this then
