### ISSUE TITLE
Meta search page results

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#84]
No space between “No matching record” and “Show” on the Result section.

![result](https://cloud.githubusercontent.com/assets/10400420/24294824/2e5c416e-10a9-11e7-9a4c-dd479b94b76b.png)

**Comment by boney-bun** [comment]
It has space between them now

![screen shot 2017-04-05 at 3 46 05 pm](https://cloud.githubusercontent.com/assets/4602383/24689253/69d196ee-1a19-11e7-8735-28358d8c62f1.png)
