### ISSUE TITLE
Filter layers on Maps page

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#86]
Map layers are not filtered. It should show only the layers related to the map. Or, does it assume that the users know what they are doing?

**Comment by lucernae** [comment]
I think geonode doesn't provide any filters for available layers. We can improve by using autocomplete or something similar.

**Comment by boney-bun** [comment]
@gubuntu @lucernae for geonode, there is a "style" options in the edit layer (see the pic to illustrate it). But it has not implemented  yet for now. I guess we can use it in the future. we can enable the style link and allow users to set the transparency. the property to set transparency is "opacity", but maybe the property is specific only for google map. I'm not sure about this.

![screen shot 2017-04-24 at 5 40 53 pm](https://cloud.githubusercontent.com/assets/4602383/25323691/445db54a-2915-11e7-939d-64db3bf81969.png)

for qgis_server, we can definitely set "LayerTransparency" in qml file. Most the qml files set the layertransparency value to 0 (no transparency). Perhaps, we can set to, let's say, 70 to make it more transparent.
The question now is: where do we want to put the transparency layer setting for qgis_server? when the users upload files or make a new menu in the UI? 

btw, I'm talking about geonode 2.6

**Comment by timlinux** [comment]
I think a nicer implementation approach would be to have some contextual menu for each layer in the map view with a slider to set individual layer transparency. This would apply only to the current map - users could still set transparency options in their layer styles if they wanted to, but the map transparency settings would be applied in addition to anything in the layer style.

**Comment by boney-bun** [comment]
I'll look at how to edit style in the layer and customize the transparency by adding a slider onto it using leaflet.
I'll make another ticket to develop client side for setting transparency in the map layer based on a discussion with @gubuntu .

**Comment by boney-bun** [comment]
I have locally activated the edit link on the style. Now, I am figuring out how to set the transparency on the "Edit" button using leaflet. 

Below is the UI. 
![screen shot 2017-04-25 at 12 24 50 am](https://cloud.githubusercontent.com/assets/4602383/25337043/40f405ce-294e-11e7-938c-9c062afd5ac5.png)

**Comment by gubuntu** [comment]
As I understand this this is affects generic geonode functionality and is not related to GeoSAFE so I am returning to backlog. Correct me if I have it wrong @MariaSolovyeva

**Comment by gubuntu** [comment]
ping @MariaSolovyeva

**Comment by MariaSolovyeva** [comment]
okay, I confirm

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#277
