### ISSUE TITLE
Legend colors on the Layer page

### ISSUE THREAD

**Issue by MariaSolovyeva** [kartoza/geosafe#87]
The colors of the Legend, particularly “Kawasan Rawan Bencana II” and “Kawasan Rawan Bencana III”, are hard to be distinguished.

![legend-layer](https://cloud.githubusercontent.com/assets/10400420/24295057/25940502-10aa-11e7-8226-6575d894af30.png)

**Comment by lucernae** [comment]
Technically, the legend is up to the user to decide (when he/she upload the layer and providing qml files).

So, CMIIW @gubuntu , I guess this is not a technical problem.

**Comment by gubuntu** [comment]
agreed
