### ISSUE TITLE
Ensure support for Internet Explorer 11 on Windows

### ISSUE THREAD

**Issue by cgiovando** [kartoza/geosafe#88]
This is (still) the default browser on many WB computers and that likely will be used for the official demo in May. Thanks for ensuring GeoSAFE functions #compatibility in addition to more modern browsers.

![image001](https://cloud.githubusercontent.com/assets/10201533/24344161/7baa5a82-12ca-11e7-9886-7c5c5aec1f4d.png)

**Comment by boney-bun** [comment]
I have tested the site using IE 11.

UPDATED: removed the shared link, put the report here.

The below explanation describes Geosafe using Internet Explorer 11 (IE 11).

The site has been tested in three different display resolutions.
In general, the Geosafe 2.6 can be viewed smoothly in IE 11, except on Upload Layer. 
The users have to upload the files one by one with a specific order.

**System Configuration**
![ie](https://cloud.githubusercontent.com/assets/4602383/24894732/64d5d148-1ee0-11e7-9b8b-1ad8cbf4fceb.PNG)
Running Windows 10 via Virtual Box 5.1.10 r112026

**Home Page in Different Resolution**
**Resolution: 1920 x 1027**

![geonodeon1920-1027](https://cloud.githubusercontent.com/assets/4602383/24894736/699f7058-1ee0-11e7-832c-fa7893d924e4.PNG)

**Resolution: 1280 x 968**

![geonodeon1280-968](https://cloud.githubusercontent.com/assets/4602383/24894749/75cd986e-1ee0-11e7-87f7-c8d94fe8ed37.PNG)

**Resolution: 800 x 600**

![geonodeon800-600](https://cloud.githubusercontent.com/assets/4602383/24894751/7a6e959e-1ee0-11e7-9303-6999482635ef.PNG)


**Passed the test case:**
* All Data links, except Upload Layer
* All Map links
* All About links
* Geosafe - Meta Search
* Geosafe - Create Analysis
* Geosafe - Analysis List
* Login, then Logout

**Failed Run Properly: Upload Layers**
When a user dragged a file in the “Drop files”, it did not work. It opened the dropped file instead.
The only option to upload layers is by selecting the files one by one via “Choose Files” button. The upload process needs to be done in a specific order, particulary it has to start with an SHP file, then the rest of the files. If the upload starts with any files but SHP files, the uploader won’t recognize them

**Comment by gubuntu** [comment]
Thanks @boney-bun please rather put that feedback directly here in GH (screenshots and all). Also, try a cross browser testing tool like the free trial of https://crossbrowsertesting.com or @timlinux can mention the one he used in Jakarta a while back. Or some more ideas in https://www.sitepoint.com/the-7-cross-browser-testing-tools-you-need-in-2016/

**Comment by timlinux** [comment]
Hi. See my notes in gitter over the weekend - we should really be using selenium and then sauce labs 

https://saucelabs.com

Saucelabs support a huge range of browser variants and it is free for FOSS projects. We really want to have these tests articulated as automated fronted tests (and we should have backend tests) otherwise we will never know when things break - running tests once off is almost useless :-P

The prototyping I did was with flask - see 

https://github.com/kartoza/osm-reporter/blob/develop/reporter/test/test_frontend.py

and 

https://scotch.io/tutorials/test-a-flask-app-with-selenium-webdriver-part-1

The concepts should be pretty similar in django - and there is an IE driver for selenium.

**Comment by boney-bun** [comment]
@gubuntu @timlinux thanks for the feedback. Then, the next target is to add selenium into the geosafe app. Also, if we have a saucelabs account, it would be great to test them.

**Comment by timlinux** [comment]
@boney-bun yeah I would suggest to do it in two steps:

1) get selenium tests running locally with a  few different drivers
2) once you have established the workflows, make it work with sauce labs so we can test on a wider range of browsers

**Comment by boney-bun** [comment]
I've added a test scenario using three browsers. 
Not completed yet.
will be revised later.

**Comment by gubuntu** [comment]
@timlinux has input regarding saucelabs free FOSS account - please proceed with this @boney-bun

**Comment by gubuntu** [comment]
also consider browserstack

**Comment by gubuntu** [comment]
we don't need to support IE 11 since  INGC staff can also use Chrome or Firefox
