### ISSUE TITLE
QGIS backend not ready for generic geonode usage

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#89]
# Problem

InaSAFE team is loading InaSAFE 4.0 training materials on http://geonode.inasafe.org yet it was recently converted to geosafe with QGIS backend. This results in at least one major negative for its intended purpose: Users cannot download conventional raster data sets. The only option is Tiles (which is also not working)

e.g. http://geonode.inasafe.org/layers/geonode:padang_population_wgs84

# Proposed solution
Redeploy geoserver geonode on this instance. 

cc: @lucernae, @timlinux, @boney-bun

**Comment by Gustry** [comment]
* @gubuntu Tiles are working, but you need to use the URL in a GIS software to manage XYZ layers : 
![capture d ecran 2017-03-27 a 20 33 01](https://cloud.githubusercontent.com/assets/1609292/24371934/b5073cfc-132c-11e7-86bb-a04cba4ecbe0.png)

* I think we can easily add a link in urls.py to download the raster? @ismailsunni ?

**Comment by gubuntu** [comment]
Thanks @Gustry 
- There should be a tip about what to do with the url and a nice message if someone clicks on it (or it shouldn't be a hyperlink). It's only natural for a user to want to click on it and expect a file to download. 
- I agree a link to download the raster should be doable. @lucernae this would be part of the layer API work under this project. Can you prioritise this?

**Comment by timlinux** [comment]
I think just fixing issues is a better approach than switching to geoserver...

**Comment by gubuntu** [comment]
being addressed in https://github.com/kartoza/geonode/issues/203
