### ISSUE TITLE
Check Layer Name

### ISSUE THREAD

**Issue by boney-bun** [kartoza/geosafe#93]
Part of resolving issue https://github.com/kartoza/geosafe/issues/85, we need to have some validation mechanism when a user upload a file. The first validation is checking if the similar layer name already exist on the system. The second one is checking if it is a valid layer and title name. 
We may need to agree whether a "good" layer name must include location and subject.

**Comment by timlinux** [comment]
I would take a different approach: When the user uploads a file there is no need for this filename to remain the same as the upload. So use either a UID (better) or the layer id as the base for the layer name - and just use the original layer name for display purposes.

**Comment by lucernae** [comment]
In geonode internal models, all where being referenced by layer name, but this is handled automatically by geonode when the layer itself where uploaded. If it is exists, they even give a suffix. The one that is used for display is called layer_title.

**Comment by boney-bun** [comment]
i think we should move this issue to geonode repo instead.
let me try to understand the logic first.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#293
