### ISSUE TITLE
UI/UX testing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#95]
with the Kartoza team, providing real use case scenarios

load a selection of Hazard layers from Labs Geonode plus the exposure layers from #96 and then write up and perform a series of tests that take you through all GeoSAFE functionality

Do this on http://staging.geonode.kartoza.com and publish the layers that pass all the tests onto http://geonode.kartoza.com

Choose sites in the Western Indian Ocean / East Africa coast incl the Comores.

Layer and analysis status is at https://docs.google.com/spreadsheets/d/1Nni6SpmTwgsOgmG2dUNj47wGzUGGHkMwT6T_7eG9s4Q/edit?usp=sharing

**Comment by gubuntu** [comment]
# Valid Hazard/Exposure combinations to test

1. Nsunga EarthQuake (raster) on Tanzania Health sites (vector point)
1. Nsunga EarthQuake (vector polygon) on Tanzania Health sites (vector point)

**Comment by NyakudyaA** [comment]
3. Nepal earthquake (vector) on Nepal buildings (vector)
4. Nepal earthquake (vector) on Nepal population rasters (different types based on year): Slow to generate output

**Comment by NyakudyaA** [comment]
Some roads layers I have loaded are not appearing in geosafe still investigating

**Comment by gubuntu** [comment]
Eric from WB will assist with testing and reporting issues. @cgiovando please assign Eric.

**Comment by gubuntu** [comment]
Erik (WB) is continuing testing but as of 6 September 2017 had positive feedback about the UI/UX.

All combinations of layers in http://geonode.kartoza.com have been tested and documented in the sheet link in the OP. 

#206 will improve response drastically once complete.
