### ISSUE TITLE
Prepare and publish datasets

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geosafe#96]
We need to prepare datasets on the hazard and exposure side to populate the Labs GeoNode

Labs Geonode (http://45.55.174.20/) has many Hazard datasets but no Exposure datasets.

We need the following layer prepared, styled and published on staging (related to #95):

Exposure
- [ ]  global population (WorldPop)
- [ ] global roads (OSM)
- [ ]  LandScan (WB has a licence so we can use it, discuss with @cgiovando)

Hazard
- see Cristiano's comment below

Layer and analysis status is at https://docs.google.com/spreadsheets/d/1Nni6SpmTwgsOgmG2dUNj47wGzUGGHkMwT6T_7eG9s4Q/edit?usp=sharing

**Comment by NyakudyaA** [comment]
Populated metadata for population data downloaded from http://sedac.ciesin.columbia.edu/data/sets/browse and http://www.worldpop.org.uk/data/data_sources/.

Tried uploading the population data. There is an upload error. I think the file size is limiting geonode upload. We need to fix this so that users are able to upload any file size.

![upload_error](https://cloud.githubusercontent.com/assets/2510900/24865999/3e0c3b92-1e09-11e7-9f43-e715c53c6420.png)

Still busy with getting global roads. Doing this as part of https://github.com/kartoza/gfdrr_oondra/issues/62#event-1036278991 As oondra was already using docker-osm

**Comment by NyakudyaA** [comment]
[](url) https://github.com/kartoza/geonode/issues/193 (error uploading large rasters)

**Comment by gubuntu** [comment]
@NyakudyaA please make the data and metadata available in a ready-to-publish form (e.g. via a resilio share) and put instructions here for exactly how to publish them on the Labs Geonode platform so that @fvanderbiest @fjacon @stufraser1 can easily publish them when they are ready.

**Comment by NyakudyaA** [comment]
I have prepared the datasets with full metadata. The datasets are available in a resilio (btsync) share using the key `BI4KJS6V75VQ22FJKGGDNNN3HCU52QES3`.  
* Sync the data to your local machine
* Copy the synced data folder  into the django container: `docker cp geosafe_data container_name:/tmp/`
*  Exec into the django container and import the data using the management commands to register the layers with geonode
 * Run `python manage.py importlayers -m data_directory` Where data_directory is the path containing the data. In this case it will be /tmp/geosafe_data

**Comment by cgiovando** [comment]
Here are the datasets to test and load for the upcoming demo:

### Hazard  

**Earthquake** (mmi units):
- [x] Tanzania: 2016 [M5.9 event](https://earthquake.usgs.gov/earthquakes/eventpage/us10006nkx#shakemap) shakemap --> [shapefile download](https://drive.google.com/open?id=0B18oUkUMksTPenFfTUZPeC1BbnM)
- [x]  Nepal: 2015 M 7.8 event shakemap --> [shapefile download](https://drive.google.com/open?id=0B18oUkUMksTPenI1b0MtREpwbzg)
- [ ]  Global shakemap API directly from [USGS service](https://usgs.github.io/shakemap/api_index.html) <-- Can we use this?

**Flood** (water depth in mm):
- [x]  Madagascar: Historical events --> [MaxDepth as point shapefile](https://drive.google.com/open?id=0B18oUkUMksTPUGVUS3RXUWk2djA)  
- [x]  Madagascar: 250-year tropical cyclone flood event --> [ESRI grid format](https://drive.google.com/open?id=0B18oUkUMksTPZndjQnUwLTdOTFk)
- [x]  Malawi: Dartmouth Flood Observatory (DFO) flood [layer](http://www.masdap.mw/layers/geonode%3A2015Malawi4219NB)
- [x]  Malawi: Radarsat flooded areas by DLR as of Jan 2015 [layer](http://www.masdap.mw/layers/geonode%3Aflood_radarsat_worldbank)

### Exposure

**Population**:
- [x]  Madagascar: Facebook/CIESIN [High Resolution Settlement Layer in GeoTIFF format](https://ciesin.columbia.edu/data/hrsl/hrsl_mdg_v1.zip) (band 1, number of persons estimated to live in each 30m pixel)
- [x]  Global: country subsets for MG, TZ and NP from WorldPop [API](https://github.com/developmentseed/worldpop) or [GeoTIFF download](http://www.worldpop.org.uk/data/data_sources/)
- [x]  Global: country subsets for MG, TZ and NP from GHSL [Population Grid](http://data.jrc.ec.europa.eu/dataset/jrc-ghsl-ghs_pop_gpw4_globe_r2015a )
- [ ]  Global: country subsets for MG, TZ and NP from Landscan ([to come](http://web.ornl.gov/sci/landscan/landscan_data_avail.shtml)): approximately 1 km resolution representing an ambient population (average over 24 hours).

**Buildings**:
- [x]  OSM subsets for MG, TZ, and NP from [GeoFabrik](http://download.geofabrik.de/africa.html)

**Roads**:
- [ ]  Global Roads Open Access Data Set (gROADS), [v1 (1980 – 2010)](http://sedac.ciesin.columbia.edu/data/set/groads-global-roads-open-access-v1/data-download)
- [x]  OSM subsets for MG, TZ, and NP from [GeoFabrik](http://download.geofabrik.de/africa.html)

**Comment by gubuntu** [comment]
@nyakudya for the OSM roads and buildings I think we should try to use the docker-osm sets you've prepared, on a per country basis until we are sure GeoSAFE can run on subsets. 

And I know we used Worldpop tifs for OONDRA but work has been done on using the API so let's try that.

**Comment by NyakudyaA** [comment]
Global Roads do not have a class that can be used to assign keywords in Inasafe. I will use Natural earth in the meantime

**Comment by cgiovando** [comment]
> I will use Natural earth in the meantime

Please use OSM instead. Thanks

**Comment by gubuntu** [comment]
large layers currently have to be loaded via backend management commands. https://github.com/kartoza/geonode/issues/52 is addressing the limitation on uploading large layers through the UI.

**Comment by NyakudyaA** [comment]
@cgiovando Any update about the Landscan data.

**Comment by cgiovando** [comment]
> Any update about the Landscan data.

@vdeparday can you comment and confirm that the license is compatible? Thanks!

**Comment by gubuntu** [comment]
all available layers are loaded with metadata populated at http://geonode.kartoza.com

**Comment by NyakudyaA** [comment]
@cgiovando what are the units for tropical cyclone. I have looked at the data source and no units are listed.
